package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.AccountRoleExample;
import com.gionee.baserom.search.pojo.AccountRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_role
	 * @mbggenerated
	 */
	int countByExample(AccountRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_role
	 * @mbggenerated
	 */
	int deleteByExample(AccountRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_role
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(AccountRoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_role
	 * @mbggenerated
	 */
	int insert(AccountRoleKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_role
	 * @mbggenerated
	 */
	int insertSelective(AccountRoleKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_role
	 * @mbggenerated
	 */
	List<AccountRoleKey> selectByExample(AccountRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_role
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AccountRoleKey record, @Param("example") AccountRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_role
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AccountRoleKey record, @Param("example") AccountRoleExample example);

	/**
	 * 根据accountId删除相应的账号的角色
	 * @param string
	 */
	void deleteByAccountId(String accountId);

	AccountRoleKey queryByAccountId(Integer accountId);

	void uppdateRoleId(AccountRoleKey ark);
}