package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.AdBehaviorTodo;
import com.gionee.baserom.search.pojo.AdBehaviorTodoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdBehaviorTodoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior_todo
	 * @mbggenerated
	 */
	int countByExample(AdBehaviorTodoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior_todo
	 * @mbggenerated
	 */
	int deleteByExample(AdBehaviorTodoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior_todo
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior_todo
	 * @mbggenerated
	 */
	int insert(AdBehaviorTodo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior_todo
	 * @mbggenerated
	 */
	int insertSelective(AdBehaviorTodo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior_todo
	 * @mbggenerated
	 */
	List<AdBehaviorTodo> selectByExample(AdBehaviorTodoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior_todo
	 * @mbggenerated
	 */
	AdBehaviorTodo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior_todo
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AdBehaviorTodo record,
			@Param("example") AdBehaviorTodoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior_todo
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AdBehaviorTodo record, @Param("example") AdBehaviorTodoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior_todo
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AdBehaviorTodo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior_todo
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AdBehaviorTodo record);

	/**
	 * 根据广告id和广告行为类型id删除广告行为信息
	 * @param adId
	 * @param adBehaviorId
	 */
	int deleteAdBehaviorTodo(@Param("adId")int adId, @Param("adBehaviorId")Integer adBehaviorId);
}