package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.AdBehavior;
import com.gionee.baserom.search.pojo.AdBehaviorExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface AdBehaviorMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior
	 * @mbggenerated
	 */
	int countByExample(AdBehaviorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior
	 * @mbggenerated
	 */
	int deleteByExample(AdBehaviorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior
	 * @mbggenerated
	 */
	int insert(AdBehavior record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior
	 * @mbggenerated
	 */
	int insertSelective(AdBehavior record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior
	 * @mbggenerated
	 */
	List<AdBehavior> selectByExample(AdBehaviorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior
	 * @mbggenerated
	 */
	AdBehavior selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AdBehavior record, @Param("example") AdBehaviorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AdBehavior record, @Param("example") AdBehaviorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AdBehavior record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_behavior
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AdBehavior record);

	/**
     * 查询分页信息
     * @param map
     * @return
     */
	List<AdBehavior> queryByPage(Map<String, Object> map);

	List<AdBehavior> getAdBehaviorList();
}