package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.AdControl;
import com.gionee.baserom.search.pojo.AdControlExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface AdControlMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_control
	 * @mbggenerated
	 */
	int countByExample(AdControlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_control
	 * @mbggenerated
	 */
	int deleteByExample(AdControlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_control
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_control
	 * @mbggenerated
	 */
	int insert(AdControl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_control
	 * @mbggenerated
	 */
	int insertSelective(AdControl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_control
	 * @mbggenerated
	 */
	List<AdControl> selectByExample(AdControlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_control
	 * @mbggenerated
	 */
	AdControl selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_control
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AdControl record, @Param("example") AdControlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_control
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AdControl record, @Param("example") AdControlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_control
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AdControl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_control
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AdControl record);

	List<AdControl> queryByPage(Map<String, Object> map);
}