package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.AdInfo;
import com.gionee.baserom.search.pojo.AdInfoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface AdInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	int countByExample(AdInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	int deleteByExample(AdInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	int insert(AdInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	int insertSelective(AdInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	List<AdInfo> selectByExample(AdInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	AdInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AdInfo record, @Param("example") AdInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AdInfo record, @Param("example") AdInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AdInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AdInfo record);

	/**
     * 查询分页信息
     * @param map
     * @return
     */
	List<AdInfo> queryByPage(Map<String, Object> map);

	/**
	 * 查询总数
	 * @param map
	 * @return
	 */
	int queryTotalCount(Map<String, Object> map);

	/**
	 * 广告投放查询总数
	 * @param map
	 * @return
	 */
	int queryTotalCountOfPuttingMag(Map<String, Object> map);

	/**
	 * 广告投放分页
	 * @param map
	 * @return
	 */
	List<AdInfo> queryByPageOfPuttingMag(Map<String, Object> map);
}