package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.AdKeyword;
import com.gionee.baserom.search.pojo.AdKeywordExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface AdKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_keyword
     *
     * @mbggenerated
     */
    int countByExample(AdKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_keyword
     *
     * @mbggenerated
     */
    int deleteByExample(AdKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_keyword
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_keyword
     *
     * @mbggenerated
     */
    int insert(AdKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_keyword
     *
     * @mbggenerated
     */
    int insertSelective(AdKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_keyword
     *
     * @mbggenerated
     */
    List<AdKeyword> selectByExample(AdKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_keyword
     *
     * @mbggenerated
     */
    AdKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_keyword
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AdKeyword record, @Param("example") AdKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_keyword
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AdKeyword record, @Param("example") AdKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_keyword
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_keyword
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdKeyword record);
    
	/**
     * 查询分页信息
     * @param map
     * @return
     */
	List<AdKeyword> queryByPage(Map<String, Object> map);

    /**
     * 获取全部
     * @return
     */
	List<AdKeyword> selectAllKeyword();

	/**
	 * 批量保存上传的关键字
	 * @param string
	 * @return
	 */
	int saveBatchKeyword(List<String> keyList);

	List<AdKeyword> getSelectedKeyword(List<String> ids);
}