package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.AdNews;
import com.gionee.baserom.search.pojo.AdNewsExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface AdNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_news
     *
     * @mbggenerated
     */
    int countByExample(AdNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_news
     *
     * @mbggenerated
     */
    int deleteByExample(AdNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_news
     *
     * @mbggenerated
     */
    int insert(AdNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_news
     *
     * @mbggenerated
     */
    int insertSelective(AdNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_news
     *
     * @mbggenerated
     */
    List<AdNews> selectByExample(AdNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_news
     *
     * @mbggenerated
     */
    AdNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_news
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AdNews record, @Param("example") AdNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_news
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AdNews record, @Param("example") AdNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdNews record);
    
    
    /**
     * 查询分页信息
     * @param map
     * @return
     */
    List<AdNews> queryByPage(Map<String, Object> map);
}