package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.AppEntrance;
import com.gionee.baserom.search.pojo.AppEntranceExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface AppEntranceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_entrance
	 * @mbggenerated
	 */
	int countByExample(AppEntranceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_entrance
	 * @mbggenerated
	 */
	int deleteByExample(AppEntranceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_entrance
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer eid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_entrance
	 * @mbggenerated
	 */
	int insert(AppEntrance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_entrance
	 * @mbggenerated
	 */
	int insertSelective(AppEntrance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_entrance
	 * @mbggenerated
	 */
	List<AppEntrance> selectByExample(AppEntranceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_entrance
	 * @mbggenerated
	 */
	AppEntrance selectByPrimaryKey(Integer eid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_entrance
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AppEntrance record, @Param("example") AppEntranceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_entrance
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AppEntrance record, @Param("example") AppEntranceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_entrance
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AppEntrance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_entrance
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AppEntrance record);

	/**
     * 查询分页信息
     * @param map
     * @return
     */
	List<AppEntrance> queryByPage(Map<String, Object> map);

	List<AppEntrance> selectAllEntrance();
}