package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.AppUri;
import com.gionee.baserom.search.pojo.AppUriExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface AppUriMapper {
    
    
    
    /*********************
     * 以下为手动加入的方法
     *********************/

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_uri
	 * @mbggenerated
	 */
	int countByExample(AppUriExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_uri
	 * @mbggenerated
	 */
	int deleteByExample(AppUriExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_uri
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_uri
	 * @mbggenerated
	 */
	int insert(AppUri record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_uri
	 * @mbggenerated
	 */
	int insertSelective(AppUri record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_uri
	 * @mbggenerated
	 */
	List<AppUri> selectByExample(AppUriExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_uri
	 * @mbggenerated
	 */
	AppUri selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_uri
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AppUri record, @Param("example") AppUriExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_uri
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AppUri record, @Param("example") AppUriExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_uri
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AppUri record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_uri
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AppUri record);

	/**
     * 查询分页信息
     * @param map
     * @return
     */
	List<AppUri> queryByPage(Map<String, Object> map);
}