package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.AppVersionEntranceExample;
import com.gionee.baserom.search.pojo.AppVersionEntranceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.gionee.baserom.search.pojo.AppVersionEntrance;

public interface AppVersionEntranceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	int countByExample(AppVersionEntranceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	int deleteByExample(AppVersionEntranceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(AppVersionEntranceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	int insert(AppVersionEntrance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	int insertSelective(AppVersionEntrance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	List<AppVersionEntrance> selectByExample(AppVersionEntranceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	AppVersionEntrance selectByPrimaryKey(AppVersionEntranceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AppVersionEntrance record,
			@Param("example") AppVersionEntranceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AppVersionEntrance record,
			@Param("example") AppVersionEntranceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AppVersionEntrance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AppVersionEntrance record);

	int deleteByVersionId(int vid);

	List<AppVersionEntrance> getVersionEntranceKeyByVid(Integer vid);
}