package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.Config;
import com.gionee.baserom.search.pojo.ConfigExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ConfigMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table config
	 * @mbggenerated
	 */
	int countByExample(ConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table config
	 * @mbggenerated
	 */
	int deleteByExample(ConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table config
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table config
	 * @mbggenerated
	 */
	int insert(Config record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table config
	 * @mbggenerated
	 */
	int insertSelective(Config record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table config
	 * @mbggenerated
	 */
	List<Config> selectByExample(ConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table config
	 * @mbggenerated
	 */
	Config selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table config
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Config record, @Param("example") ConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table config
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Config record, @Param("example") ConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table config
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Config record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table config
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Config record);
	
	/*********************
     * 以下为手动加入的方法
     *********************/

	/**
     * 查询分页信息
     * @param map
     * @return
     */
	List<Config> queryByPage(Map<String, Object> map);
}