package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.Resources;
import com.gionee.baserom.search.pojo.ResourcesExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ResourcesMapper {
    
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	int countByExample(ResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	int deleteByExample(ResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	int insert(Resources record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	int insertSelective(Resources record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	List<Resources> selectByExample(ResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	Resources selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Resources record, @Param("example") ResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Resources record, @Param("example") ResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Resources record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Resources record);

	/**
     * 查询分页信息
     * @param map
     * @return
     */
	List<Resources> queryByPage(Map<String, Object> map);
	
	/**
	 * 根据用户Id获取该用户的权限
	 * @param valueOf
	 * @return
	 */
	List<Resources> getAccountResources(String accountId);

	/**
	 * 查询全部
	 * @return
	 */
	List<Resources> findAll();

	/**
	 * 根据角色id查询相关资源
	 * @param roleId
	 * @return
	 */
	List<Resources> queryByRoleId(int roleId);

	/**
	 * 根据resId 查询总数
	 * @param resId
	 * @return
	 */
	int selectTotalCount(Map<String, Object> map);

	/**
	 * 根据账号id查询该账号下的可访问资源
	 * @param id
	 * @return
	 */
	List<Resources> queryAccountMenu(Integer id);

	/**
	 * 根据账号id查询该账号下对应该菜单的按钮
	 * @param id
	 * @return
	 */
	List<Resources> queryAccountOpt(@Param("accId")int accId, @Param("resId")int resId);
}