package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.ResourcesRoleExample;
import com.gionee.baserom.search.pojo.ResourcesRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourcesRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_role
     *
     * @mbggenerated
     */
    int countByExample(ResourcesRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_role
     *
     * @mbggenerated
     */
    int deleteByExample(ResourcesRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ResourcesRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_role
     *
     * @mbggenerated
     */
    int insert(ResourcesRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_role
     *
     * @mbggenerated
     */
    int insertSelective(ResourcesRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_role
     *
     * @mbggenerated
     */
    List<ResourcesRoleKey> selectByExample(ResourcesRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ResourcesRoleKey record, @Param("example") ResourcesRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ResourcesRoleKey record, @Param("example") ResourcesRoleExample example);

    /**
     * delete by role_id
     * @param roleId
     */
	void deleteByRoleId(int roleId);
}