package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.SiteNavigation;
import com.gionee.baserom.search.pojo.SiteNavigationExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SiteNavigationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	int countByExample(SiteNavigationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	int deleteByExample(SiteNavigationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	int insert(SiteNavigation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	int insertSelective(SiteNavigation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	List<SiteNavigation> selectByExampleWithBLOBs(SiteNavigationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	List<SiteNavigation> selectByExample(SiteNavigationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	SiteNavigation selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SiteNavigation record,
			@Param("example") SiteNavigationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(@Param("record") SiteNavigation record,
			@Param("example") SiteNavigationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SiteNavigation record, @Param("example") SiteNavigationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SiteNavigation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(SiteNavigation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SiteNavigation record);

	/**
     * 查询分页信息
     * @param map
     * @return
     */
	List<SiteNavigation> queryByPage(Map<String, Object> map);
}