package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.SysDictionaryClassify;
import com.gionee.baserom.search.pojo.SysDictionaryClassifyExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysDictionaryClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_classify
     *
     * @mbggenerated
     */
    int countByExample(SysDictionaryClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_classify
     *
     * @mbggenerated
     */
    int deleteByExample(SysDictionaryClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_classify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_classify
     *
     * @mbggenerated
     */
    int insert(SysDictionaryClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_classify
     *
     * @mbggenerated
     */
    int insertSelective(SysDictionaryClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_classify
     *
     * @mbggenerated
     */
    List<SysDictionaryClassify> selectByExample(SysDictionaryClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_classify
     *
     * @mbggenerated
     */
    SysDictionaryClassify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_classify
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysDictionaryClassify record, @Param("example") SysDictionaryClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_classify
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysDictionaryClassify record, @Param("example") SysDictionaryClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_classify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysDictionaryClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary_classify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysDictionaryClassify record);
    
    /*********************
     * 以下为手动加入的方法
     *********************/

	/**
     * 查询分页信息
     * @param map
     * @return
     */
	List<SysDictionaryClassify> queryByPage(Map<String, Object> map);

	List<SysDictionaryClassify> queryAllClassify();

	List<SysDictionaryClassify> getDictionaryData();
}