package com.gionee.baserom.search.dao;

import com.gionee.baserom.search.pojo.SysDictionary;
import com.gionee.baserom.search.pojo.SysDictionaryExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysDictionaryMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dictionary
	 * @mbggenerated
	 */
	int countByExample(SysDictionaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dictionary
	 * @mbggenerated
	 */
	int deleteByExample(SysDictionaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dictionary
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dictionary
	 * @mbggenerated
	 */
	int insert(SysDictionary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dictionary
	 * @mbggenerated
	 */
	int insertSelective(SysDictionary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dictionary
	 * @mbggenerated
	 */
	List<SysDictionary> selectByExample(SysDictionaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dictionary
	 * @mbggenerated
	 */
	SysDictionary selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dictionary
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") SysDictionary record, @Param("example") SysDictionaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dictionary
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") SysDictionary record, @Param("example") SysDictionaryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dictionary
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysDictionary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dictionary
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysDictionary record);

	/**
     * 查询分页信息
     * @param map
     * @return
     */
	List<SysDictionary> queryByPage(Map<String, Object> map);

	List<SysDictionary> selectByClassifyRef(String refkey);

	/**
	 * 获取版本字典
	 * @return
	 */
	List<SysDictionary> queryByDicKeyVersion();
	List<SysDictionary> queryByDicKeyMechineType();

	List<SysDictionary> selectByIds(List<String> list);

	List<SysDictionary> querySelectedMechineType(List<String> ids);
}