package com.gionee.baserom.search.pojo;

public class AccountRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_role.account_id
	 * @mbggenerated
	 */
	private Integer accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_role.role_id
	 * @mbggenerated
	 */
	private Integer roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_role.account_id
	 * @return  the value of account_role.account_id
	 * @mbggenerated
	 */
	public Integer getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_role.account_id
	 * @param accountId  the value for account_role.account_id
	 * @mbggenerated
	 */
	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_role.role_id
	 * @return  the value of account_role.role_id
	 * @mbggenerated
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_role.role_id
	 * @param roleId  the value for account_role.role_id
	 * @mbggenerated
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}
}