package com.gionee.baserom.search.pojo;

public class AdBehaviorTodo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_behavior_todo.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_behavior_todo.ad_behavior_id
	 * @mbggenerated
	 */
	private Integer adBehaviorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_behavior_todo.ad_id
	 * @mbggenerated
	 */
	private Integer adId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_behavior_todo.url
	 * @mbggenerated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_behavior_todo.app_name
	 * @mbggenerated
	 */
	private String appName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_behavior_todo.id
	 * @return  the value of ad_behavior_todo.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_behavior_todo.id
	 * @param id  the value for ad_behavior_todo.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_behavior_todo.ad_behavior_id
	 * @return  the value of ad_behavior_todo.ad_behavior_id
	 * @mbggenerated
	 */
	public Integer getAdBehaviorId() {
		return adBehaviorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_behavior_todo.ad_behavior_id
	 * @param adBehaviorId  the value for ad_behavior_todo.ad_behavior_id
	 * @mbggenerated
	 */
	public void setAdBehaviorId(Integer adBehaviorId) {
		this.adBehaviorId = adBehaviorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_behavior_todo.ad_id
	 * @return  the value of ad_behavior_todo.ad_id
	 * @mbggenerated
	 */
	public Integer getAdId() {
		return adId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_behavior_todo.ad_id
	 * @param adId  the value for ad_behavior_todo.ad_id
	 * @mbggenerated
	 */
	public void setAdId(Integer adId) {
		this.adId = adId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_behavior_todo.url
	 * @return  the value of ad_behavior_todo.url
	 * @mbggenerated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_behavior_todo.url
	 * @param url  the value for ad_behavior_todo.url
	 * @mbggenerated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_behavior_todo.app_name
	 * @return  the value of ad_behavior_todo.app_name
	 * @mbggenerated
	 */
	public String getAppName() {
		return appName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_behavior_todo.app_name
	 * @param appName  the value for ad_behavior_todo.app_name
	 * @mbggenerated
	 */
	public void setAppName(String appName) {
		this.appName = appName == null ? null : appName.trim();
	}
}