package com.gionee.baserom.search.pojo;

public class AdBehavior {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_behavior.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_behavior.behavior
	 * @mbggenerated
	 */
	private String behavior;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_behavior.is_download_app
	 * @mbggenerated
	 */
	private Integer isDownloadApp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_behavior.id
	 * @return  the value of ad_behavior.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_behavior.id
	 * @param id  the value for ad_behavior.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_behavior.behavior
	 * @return  the value of ad_behavior.behavior
	 * @mbggenerated
	 */
	public String getBehavior() {
		return behavior;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_behavior.behavior
	 * @param behavior  the value for ad_behavior.behavior
	 * @mbggenerated
	 */
	public void setBehavior(String behavior) {
		this.behavior = behavior == null ? null : behavior.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_behavior.is_download_app
	 * @return  the value of ad_behavior.is_download_app
	 * @mbggenerated
	 */
	public Integer getIsDownloadApp() {
		return isDownloadApp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_behavior.is_download_app
	 * @param isDownloadApp  the value for ad_behavior.is_download_app
	 * @mbggenerated
	 */
	public void setIsDownloadApp(Integer isDownloadApp) {
		this.isDownloadApp = isDownloadApp;
	}
}