package com.gionee.baserom.search.pojo;

public class AdClassify {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_classify.cid
	 * @mbggenerated
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_classify.cname
	 * @mbggenerated
	 */
	private String cname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_classify.cid
	 * @return  the value of ad_classify.cid
	 * @mbggenerated
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_classify.cid
	 * @param cid  the value for ad_classify.cid
	 * @mbggenerated
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_classify.cname
	 * @return  the value of ad_classify.cname
	 * @mbggenerated
	 */
	public String getCname() {
		return cname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_classify.cname
	 * @param cname  the value for ad_classify.cname
	 * @mbggenerated
	 */
	public void setCname(String cname) {
		this.cname = cname == null ? null : cname.trim();
	}
}