package com.gionee.baserom.search.pojo;

public class AdControl {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_control.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_control.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_control.show_flag
	 * @mbggenerated
	 */
	private Integer showFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_control.position_id
	 * @mbggenerated
	 */
	private Integer positionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_control.ad_img
	 * @mbggenerated
	 */
	private String adImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_control.ad_url
	 * @mbggenerated
	 */
	private String adUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_control.id
	 * @return  the value of ad_control.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_control.id
	 * @param id  the value for ad_control.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_control.name
	 * @return  the value of ad_control.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_control.name
	 * @param name  the value for ad_control.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_control.show_flag
	 * @return  the value of ad_control.show_flag
	 * @mbggenerated
	 */
	public Integer getShowFlag() {
		return showFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_control.show_flag
	 * @param showFlag  the value for ad_control.show_flag
	 * @mbggenerated
	 */
	public void setShowFlag(Integer showFlag) {
		this.showFlag = showFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_control.position_id
	 * @return  the value of ad_control.position_id
	 * @mbggenerated
	 */
	public Integer getPositionId() {
		return positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_control.position_id
	 * @param positionId  the value for ad_control.position_id
	 * @mbggenerated
	 */
	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_control.ad_img
	 * @return  the value of ad_control.ad_img
	 * @mbggenerated
	 */
	public String getAdImg() {
		return adImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_control.ad_img
	 * @param adImg  the value for ad_control.ad_img
	 * @mbggenerated
	 */
	public void setAdImg(String adImg) {
		this.adImg = adImg == null ? null : adImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_control.ad_url
	 * @return  the value of ad_control.ad_url
	 * @mbggenerated
	 */
	public String getAdUrl() {
		return adUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_control.ad_url
	 * @param adUrl  the value for ad_control.ad_url
	 * @mbggenerated
	 */
	public void setAdUrl(String adUrl) {
		this.adUrl = adUrl == null ? null : adUrl.trim();
	}
}