package com.gionee.baserom.search.pojo;

public class AdDisplayRule {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_display_rule.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_display_rule.ad_position
	 * @mbggenerated
	 */
	private String adPosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_display_rule.dic_id
	 * @mbggenerated
	 */
	private Integer dicId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_display_rule.min_weight
	 * @mbggenerated
	 */
	private Integer minWeight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_display_rule.max_weight
	 * @mbggenerated
	 */
	private Integer maxWeight;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_display_rule.id
	 * @return  the value of ad_display_rule.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_display_rule.id
	 * @param id  the value for ad_display_rule.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_display_rule.ad_position
	 * @return  the value of ad_display_rule.ad_position
	 * @mbggenerated
	 */
	public String getAdPosition() {
		return adPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_display_rule.ad_position
	 * @param adPosition  the value for ad_display_rule.ad_position
	 * @mbggenerated
	 */
	public void setAdPosition(String adPosition) {
		this.adPosition = adPosition == null ? null : adPosition.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_display_rule.dic_id
	 * @return  the value of ad_display_rule.dic_id
	 * @mbggenerated
	 */
	public Integer getDicId() {
		return dicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_display_rule.dic_id
	 * @param dicId  the value for ad_display_rule.dic_id
	 * @mbggenerated
	 */
	public void setDicId(Integer dicId) {
		this.dicId = dicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_display_rule.min_weight
	 * @return  the value of ad_display_rule.min_weight
	 * @mbggenerated
	 */
	public Integer getMinWeight() {
		return minWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_display_rule.min_weight
	 * @param minWeight  the value for ad_display_rule.min_weight
	 * @mbggenerated
	 */
	public void setMinWeight(Integer minWeight) {
		this.minWeight = minWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_display_rule.max_weight
	 * @return  the value of ad_display_rule.max_weight
	 * @mbggenerated
	 */
	public Integer getMaxWeight() {
		return maxWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_display_rule.max_weight
	 * @param maxWeight  the value for ad_display_rule.max_weight
	 * @mbggenerated
	 */
	public void setMaxWeight(Integer maxWeight) {
		this.maxWeight = maxWeight;
	}

	private SysDictionary adTypeObj;

	public SysDictionary getAdTypeObj() {
		return adTypeObj;
	}

	public void setAdTypeObj(SysDictionary adTypeObj) {
		this.adTypeObj = adTypeObj;
	}
}