package com.gionee.baserom.search.pojo;

import java.util.ArrayList;
import java.util.List;

public class AdDisplayRuleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	public AdDisplayRuleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAdPositionIsNull() {
			addCriterion("ad_position is null");
			return (Criteria) this;
		}

		public Criteria andAdPositionIsNotNull() {
			addCriterion("ad_position is not null");
			return (Criteria) this;
		}

		public Criteria andAdPositionEqualTo(String value) {
			addCriterion("ad_position =", value, "adPosition");
			return (Criteria) this;
		}

		public Criteria andAdPositionNotEqualTo(String value) {
			addCriterion("ad_position <>", value, "adPosition");
			return (Criteria) this;
		}

		public Criteria andAdPositionGreaterThan(String value) {
			addCriterion("ad_position >", value, "adPosition");
			return (Criteria) this;
		}

		public Criteria andAdPositionGreaterThanOrEqualTo(String value) {
			addCriterion("ad_position >=", value, "adPosition");
			return (Criteria) this;
		}

		public Criteria andAdPositionLessThan(String value) {
			addCriterion("ad_position <", value, "adPosition");
			return (Criteria) this;
		}

		public Criteria andAdPositionLessThanOrEqualTo(String value) {
			addCriterion("ad_position <=", value, "adPosition");
			return (Criteria) this;
		}

		public Criteria andAdPositionLike(String value) {
			addCriterion("ad_position like", value, "adPosition");
			return (Criteria) this;
		}

		public Criteria andAdPositionNotLike(String value) {
			addCriterion("ad_position not like", value, "adPosition");
			return (Criteria) this;
		}

		public Criteria andAdPositionIn(List<String> values) {
			addCriterion("ad_position in", values, "adPosition");
			return (Criteria) this;
		}

		public Criteria andAdPositionNotIn(List<String> values) {
			addCriterion("ad_position not in", values, "adPosition");
			return (Criteria) this;
		}

		public Criteria andAdPositionBetween(String value1, String value2) {
			addCriterion("ad_position between", value1, value2, "adPosition");
			return (Criteria) this;
		}

		public Criteria andAdPositionNotBetween(String value1, String value2) {
			addCriterion("ad_position not between", value1, value2, "adPosition");
			return (Criteria) this;
		}

		public Criteria andDicIdIsNull() {
			addCriterion("dic_id is null");
			return (Criteria) this;
		}

		public Criteria andDicIdIsNotNull() {
			addCriterion("dic_id is not null");
			return (Criteria) this;
		}

		public Criteria andDicIdEqualTo(Integer value) {
			addCriterion("dic_id =", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdNotEqualTo(Integer value) {
			addCriterion("dic_id <>", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdGreaterThan(Integer value) {
			addCriterion("dic_id >", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("dic_id >=", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdLessThan(Integer value) {
			addCriterion("dic_id <", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdLessThanOrEqualTo(Integer value) {
			addCriterion("dic_id <=", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdIn(List<Integer> values) {
			addCriterion("dic_id in", values, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdNotIn(List<Integer> values) {
			addCriterion("dic_id not in", values, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdBetween(Integer value1, Integer value2) {
			addCriterion("dic_id between", value1, value2, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdNotBetween(Integer value1, Integer value2) {
			addCriterion("dic_id not between", value1, value2, "dicId");
			return (Criteria) this;
		}

		public Criteria andMinWeightIsNull() {
			addCriterion("min_weight is null");
			return (Criteria) this;
		}

		public Criteria andMinWeightIsNotNull() {
			addCriterion("min_weight is not null");
			return (Criteria) this;
		}

		public Criteria andMinWeightEqualTo(Integer value) {
			addCriterion("min_weight =", value, "minWeight");
			return (Criteria) this;
		}

		public Criteria andMinWeightNotEqualTo(Integer value) {
			addCriterion("min_weight <>", value, "minWeight");
			return (Criteria) this;
		}

		public Criteria andMinWeightGreaterThan(Integer value) {
			addCriterion("min_weight >", value, "minWeight");
			return (Criteria) this;
		}

		public Criteria andMinWeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("min_weight >=", value, "minWeight");
			return (Criteria) this;
		}

		public Criteria andMinWeightLessThan(Integer value) {
			addCriterion("min_weight <", value, "minWeight");
			return (Criteria) this;
		}

		public Criteria andMinWeightLessThanOrEqualTo(Integer value) {
			addCriterion("min_weight <=", value, "minWeight");
			return (Criteria) this;
		}

		public Criteria andMinWeightIn(List<Integer> values) {
			addCriterion("min_weight in", values, "minWeight");
			return (Criteria) this;
		}

		public Criteria andMinWeightNotIn(List<Integer> values) {
			addCriterion("min_weight not in", values, "minWeight");
			return (Criteria) this;
		}

		public Criteria andMinWeightBetween(Integer value1, Integer value2) {
			addCriterion("min_weight between", value1, value2, "minWeight");
			return (Criteria) this;
		}

		public Criteria andMinWeightNotBetween(Integer value1, Integer value2) {
			addCriterion("min_weight not between", value1, value2, "minWeight");
			return (Criteria) this;
		}

		public Criteria andMaxWeightIsNull() {
			addCriterion("max_weight is null");
			return (Criteria) this;
		}

		public Criteria andMaxWeightIsNotNull() {
			addCriterion("max_weight is not null");
			return (Criteria) this;
		}

		public Criteria andMaxWeightEqualTo(Integer value) {
			addCriterion("max_weight =", value, "maxWeight");
			return (Criteria) this;
		}

		public Criteria andMaxWeightNotEqualTo(Integer value) {
			addCriterion("max_weight <>", value, "maxWeight");
			return (Criteria) this;
		}

		public Criteria andMaxWeightGreaterThan(Integer value) {
			addCriterion("max_weight >", value, "maxWeight");
			return (Criteria) this;
		}

		public Criteria andMaxWeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("max_weight >=", value, "maxWeight");
			return (Criteria) this;
		}

		public Criteria andMaxWeightLessThan(Integer value) {
			addCriterion("max_weight <", value, "maxWeight");
			return (Criteria) this;
		}

		public Criteria andMaxWeightLessThanOrEqualTo(Integer value) {
			addCriterion("max_weight <=", value, "maxWeight");
			return (Criteria) this;
		}

		public Criteria andMaxWeightIn(List<Integer> values) {
			addCriterion("max_weight in", values, "maxWeight");
			return (Criteria) this;
		}

		public Criteria andMaxWeightNotIn(List<Integer> values) {
			addCriterion("max_weight not in", values, "maxWeight");
			return (Criteria) this;
		}

		public Criteria andMaxWeightBetween(Integer value1, Integer value2) {
			addCriterion("max_weight between", value1, value2, "maxWeight");
			return (Criteria) this;
		}

		public Criteria andMaxWeightNotBetween(Integer value1, Integer value2) {
			addCriterion("max_weight not between", value1, value2, "maxWeight");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ad_display_rule
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ad_display_rule
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}