package com.gionee.baserom.search.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ad_info
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ad_info
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ad_info
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	public AdInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_info
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ad_info
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAdRuleIdIsNull() {
			addCriterion("ad_rule_id is null");
			return (Criteria) this;
		}

		public Criteria andAdRuleIdIsNotNull() {
			addCriterion("ad_rule_id is not null");
			return (Criteria) this;
		}

		public Criteria andAdRuleIdEqualTo(Integer value) {
			addCriterion("ad_rule_id =", value, "adRuleId");
			return (Criteria) this;
		}

		public Criteria andAdRuleIdNotEqualTo(Integer value) {
			addCriterion("ad_rule_id <>", value, "adRuleId");
			return (Criteria) this;
		}

		public Criteria andAdRuleIdGreaterThan(Integer value) {
			addCriterion("ad_rule_id >", value, "adRuleId");
			return (Criteria) this;
		}

		public Criteria andAdRuleIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ad_rule_id >=", value, "adRuleId");
			return (Criteria) this;
		}

		public Criteria andAdRuleIdLessThan(Integer value) {
			addCriterion("ad_rule_id <", value, "adRuleId");
			return (Criteria) this;
		}

		public Criteria andAdRuleIdLessThanOrEqualTo(Integer value) {
			addCriterion("ad_rule_id <=", value, "adRuleId");
			return (Criteria) this;
		}

		public Criteria andAdRuleIdIn(List<Integer> values) {
			addCriterion("ad_rule_id in", values, "adRuleId");
			return (Criteria) this;
		}

		public Criteria andAdRuleIdNotIn(List<Integer> values) {
			addCriterion("ad_rule_id not in", values, "adRuleId");
			return (Criteria) this;
		}

		public Criteria andAdRuleIdBetween(Integer value1, Integer value2) {
			addCriterion("ad_rule_id between", value1, value2, "adRuleId");
			return (Criteria) this;
		}

		public Criteria andAdRuleIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ad_rule_id not between", value1, value2, "adRuleId");
			return (Criteria) this;
		}

		public Criteria andAdTittleIsNull() {
			addCriterion("ad_tittle is null");
			return (Criteria) this;
		}

		public Criteria andAdTittleIsNotNull() {
			addCriterion("ad_tittle is not null");
			return (Criteria) this;
		}

		public Criteria andAdTittleEqualTo(String value) {
			addCriterion("ad_tittle =", value, "adTittle");
			return (Criteria) this;
		}

		public Criteria andAdTittleNotEqualTo(String value) {
			addCriterion("ad_tittle <>", value, "adTittle");
			return (Criteria) this;
		}

		public Criteria andAdTittleGreaterThan(String value) {
			addCriterion("ad_tittle >", value, "adTittle");
			return (Criteria) this;
		}

		public Criteria andAdTittleGreaterThanOrEqualTo(String value) {
			addCriterion("ad_tittle >=", value, "adTittle");
			return (Criteria) this;
		}

		public Criteria andAdTittleLessThan(String value) {
			addCriterion("ad_tittle <", value, "adTittle");
			return (Criteria) this;
		}

		public Criteria andAdTittleLessThanOrEqualTo(String value) {
			addCriterion("ad_tittle <=", value, "adTittle");
			return (Criteria) this;
		}

		public Criteria andAdTittleLike(String value) {
			addCriterion("ad_tittle like", value, "adTittle");
			return (Criteria) this;
		}

		public Criteria andAdTittleNotLike(String value) {
			addCriterion("ad_tittle not like", value, "adTittle");
			return (Criteria) this;
		}

		public Criteria andAdTittleIn(List<String> values) {
			addCriterion("ad_tittle in", values, "adTittle");
			return (Criteria) this;
		}

		public Criteria andAdTittleNotIn(List<String> values) {
			addCriterion("ad_tittle not in", values, "adTittle");
			return (Criteria) this;
		}

		public Criteria andAdTittleBetween(String value1, String value2) {
			addCriterion("ad_tittle between", value1, value2, "adTittle");
			return (Criteria) this;
		}

		public Criteria andAdTittleNotBetween(String value1, String value2) {
			addCriterion("ad_tittle not between", value1, value2, "adTittle");
			return (Criteria) this;
		}

		public Criteria andShowTittleFlagIsNull() {
			addCriterion("show_tittle_flag is null");
			return (Criteria) this;
		}

		public Criteria andShowTittleFlagIsNotNull() {
			addCriterion("show_tittle_flag is not null");
			return (Criteria) this;
		}

		public Criteria andShowTittleFlagEqualTo(Integer value) {
			addCriterion("show_tittle_flag =", value, "showTittleFlag");
			return (Criteria) this;
		}

		public Criteria andShowTittleFlagNotEqualTo(Integer value) {
			addCriterion("show_tittle_flag <>", value, "showTittleFlag");
			return (Criteria) this;
		}

		public Criteria andShowTittleFlagGreaterThan(Integer value) {
			addCriterion("show_tittle_flag >", value, "showTittleFlag");
			return (Criteria) this;
		}

		public Criteria andShowTittleFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("show_tittle_flag >=", value, "showTittleFlag");
			return (Criteria) this;
		}

		public Criteria andShowTittleFlagLessThan(Integer value) {
			addCriterion("show_tittle_flag <", value, "showTittleFlag");
			return (Criteria) this;
		}

		public Criteria andShowTittleFlagLessThanOrEqualTo(Integer value) {
			addCriterion("show_tittle_flag <=", value, "showTittleFlag");
			return (Criteria) this;
		}

		public Criteria andShowTittleFlagIn(List<Integer> values) {
			addCriterion("show_tittle_flag in", values, "showTittleFlag");
			return (Criteria) this;
		}

		public Criteria andShowTittleFlagNotIn(List<Integer> values) {
			addCriterion("show_tittle_flag not in", values, "showTittleFlag");
			return (Criteria) this;
		}

		public Criteria andShowTittleFlagBetween(Integer value1, Integer value2) {
			addCriterion("show_tittle_flag between", value1, value2, "showTittleFlag");
			return (Criteria) this;
		}

		public Criteria andShowTittleFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("show_tittle_flag not between", value1, value2, "showTittleFlag");
			return (Criteria) this;
		}

		public Criteria andCpNameIsNull() {
			addCriterion("cp_name is null");
			return (Criteria) this;
		}

		public Criteria andCpNameIsNotNull() {
			addCriterion("cp_name is not null");
			return (Criteria) this;
		}

		public Criteria andCpNameEqualTo(String value) {
			addCriterion("cp_name =", value, "cpName");
			return (Criteria) this;
		}

		public Criteria andCpNameNotEqualTo(String value) {
			addCriterion("cp_name <>", value, "cpName");
			return (Criteria) this;
		}

		public Criteria andCpNameGreaterThan(String value) {
			addCriterion("cp_name >", value, "cpName");
			return (Criteria) this;
		}

		public Criteria andCpNameGreaterThanOrEqualTo(String value) {
			addCriterion("cp_name >=", value, "cpName");
			return (Criteria) this;
		}

		public Criteria andCpNameLessThan(String value) {
			addCriterion("cp_name <", value, "cpName");
			return (Criteria) this;
		}

		public Criteria andCpNameLessThanOrEqualTo(String value) {
			addCriterion("cp_name <=", value, "cpName");
			return (Criteria) this;
		}

		public Criteria andCpNameLike(String value) {
			addCriterion("cp_name like", value, "cpName");
			return (Criteria) this;
		}

		public Criteria andCpNameNotLike(String value) {
			addCriterion("cp_name not like", value, "cpName");
			return (Criteria) this;
		}

		public Criteria andCpNameIn(List<String> values) {
			addCriterion("cp_name in", values, "cpName");
			return (Criteria) this;
		}

		public Criteria andCpNameNotIn(List<String> values) {
			addCriterion("cp_name not in", values, "cpName");
			return (Criteria) this;
		}

		public Criteria andCpNameBetween(String value1, String value2) {
			addCriterion("cp_name between", value1, value2, "cpName");
			return (Criteria) this;
		}

		public Criteria andCpNameNotBetween(String value1, String value2) {
			addCriterion("cp_name not between", value1, value2, "cpName");
			return (Criteria) this;
		}

		public Criteria andSpecificationIsNull() {
			addCriterion("specification is null");
			return (Criteria) this;
		}

		public Criteria andSpecificationIsNotNull() {
			addCriterion("specification is not null");
			return (Criteria) this;
		}

		public Criteria andSpecificationEqualTo(Integer value) {
			addCriterion("specification =", value, "specification");
			return (Criteria) this;
		}

		public Criteria andSpecificationNotEqualTo(Integer value) {
			addCriterion("specification <>", value, "specification");
			return (Criteria) this;
		}

		public Criteria andSpecificationGreaterThan(Integer value) {
			addCriterion("specification >", value, "specification");
			return (Criteria) this;
		}

		public Criteria andSpecificationGreaterThanOrEqualTo(Integer value) {
			addCriterion("specification >=", value, "specification");
			return (Criteria) this;
		}

		public Criteria andSpecificationLessThan(Integer value) {
			addCriterion("specification <", value, "specification");
			return (Criteria) this;
		}

		public Criteria andSpecificationLessThanOrEqualTo(Integer value) {
			addCriterion("specification <=", value, "specification");
			return (Criteria) this;
		}

		public Criteria andSpecificationIn(List<Integer> values) {
			addCriterion("specification in", values, "specification");
			return (Criteria) this;
		}

		public Criteria andSpecificationNotIn(List<Integer> values) {
			addCriterion("specification not in", values, "specification");
			return (Criteria) this;
		}

		public Criteria andSpecificationBetween(Integer value1, Integer value2) {
			addCriterion("specification between", value1, value2, "specification");
			return (Criteria) this;
		}

		public Criteria andSpecificationNotBetween(Integer value1, Integer value2) {
			addCriterion("specification not between", value1, value2, "specification");
			return (Criteria) this;
		}

		public Criteria andAdImagePathIsNull() {
			addCriterion("ad_image_path is null");
			return (Criteria) this;
		}

		public Criteria andAdImagePathIsNotNull() {
			addCriterion("ad_image_path is not null");
			return (Criteria) this;
		}

		public Criteria andAdImagePathEqualTo(String value) {
			addCriterion("ad_image_path =", value, "adImagePath");
			return (Criteria) this;
		}

		public Criteria andAdImagePathNotEqualTo(String value) {
			addCriterion("ad_image_path <>", value, "adImagePath");
			return (Criteria) this;
		}

		public Criteria andAdImagePathGreaterThan(String value) {
			addCriterion("ad_image_path >", value, "adImagePath");
			return (Criteria) this;
		}

		public Criteria andAdImagePathGreaterThanOrEqualTo(String value) {
			addCriterion("ad_image_path >=", value, "adImagePath");
			return (Criteria) this;
		}

		public Criteria andAdImagePathLessThan(String value) {
			addCriterion("ad_image_path <", value, "adImagePath");
			return (Criteria) this;
		}

		public Criteria andAdImagePathLessThanOrEqualTo(String value) {
			addCriterion("ad_image_path <=", value, "adImagePath");
			return (Criteria) this;
		}

		public Criteria andAdImagePathLike(String value) {
			addCriterion("ad_image_path like", value, "adImagePath");
			return (Criteria) this;
		}

		public Criteria andAdImagePathNotLike(String value) {
			addCriterion("ad_image_path not like", value, "adImagePath");
			return (Criteria) this;
		}

		public Criteria andAdImagePathIn(List<String> values) {
			addCriterion("ad_image_path in", values, "adImagePath");
			return (Criteria) this;
		}

		public Criteria andAdImagePathNotIn(List<String> values) {
			addCriterion("ad_image_path not in", values, "adImagePath");
			return (Criteria) this;
		}

		public Criteria andAdImagePathBetween(String value1, String value2) {
			addCriterion("ad_image_path between", value1, value2, "adImagePath");
			return (Criteria) this;
		}

		public Criteria andAdImagePathNotBetween(String value1, String value2) {
			addCriterion("ad_image_path not between", value1, value2, "adImagePath");
			return (Criteria) this;
		}

		public Criteria andAdBehaviorIdIsNull() {
			addCriterion("ad_behavior_id is null");
			return (Criteria) this;
		}

		public Criteria andAdBehaviorIdIsNotNull() {
			addCriterion("ad_behavior_id is not null");
			return (Criteria) this;
		}

		public Criteria andAdBehaviorIdEqualTo(Integer value) {
			addCriterion("ad_behavior_id =", value, "adBehaviorId");
			return (Criteria) this;
		}

		public Criteria andAdBehaviorIdNotEqualTo(Integer value) {
			addCriterion("ad_behavior_id <>", value, "adBehaviorId");
			return (Criteria) this;
		}

		public Criteria andAdBehaviorIdGreaterThan(Integer value) {
			addCriterion("ad_behavior_id >", value, "adBehaviorId");
			return (Criteria) this;
		}

		public Criteria andAdBehaviorIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ad_behavior_id >=", value, "adBehaviorId");
			return (Criteria) this;
		}

		public Criteria andAdBehaviorIdLessThan(Integer value) {
			addCriterion("ad_behavior_id <", value, "adBehaviorId");
			return (Criteria) this;
		}

		public Criteria andAdBehaviorIdLessThanOrEqualTo(Integer value) {
			addCriterion("ad_behavior_id <=", value, "adBehaviorId");
			return (Criteria) this;
		}

		public Criteria andAdBehaviorIdIn(List<Integer> values) {
			addCriterion("ad_behavior_id in", values, "adBehaviorId");
			return (Criteria) this;
		}

		public Criteria andAdBehaviorIdNotIn(List<Integer> values) {
			addCriterion("ad_behavior_id not in", values, "adBehaviorId");
			return (Criteria) this;
		}

		public Criteria andAdBehaviorIdBetween(Integer value1, Integer value2) {
			addCriterion("ad_behavior_id between", value1, value2, "adBehaviorId");
			return (Criteria) this;
		}

		public Criteria andAdBehaviorIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ad_behavior_id not between", value1, value2, "adBehaviorId");
			return (Criteria) this;
		}

		public Criteria andAdClassifyIdIsNull() {
			addCriterion("ad_classify_id is null");
			return (Criteria) this;
		}

		public Criteria andAdClassifyIdIsNotNull() {
			addCriterion("ad_classify_id is not null");
			return (Criteria) this;
		}

		public Criteria andAdClassifyIdEqualTo(Integer value) {
			addCriterion("ad_classify_id =", value, "adClassifyId");
			return (Criteria) this;
		}

		public Criteria andAdClassifyIdNotEqualTo(Integer value) {
			addCriterion("ad_classify_id <>", value, "adClassifyId");
			return (Criteria) this;
		}

		public Criteria andAdClassifyIdGreaterThan(Integer value) {
			addCriterion("ad_classify_id >", value, "adClassifyId");
			return (Criteria) this;
		}

		public Criteria andAdClassifyIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ad_classify_id >=", value, "adClassifyId");
			return (Criteria) this;
		}

		public Criteria andAdClassifyIdLessThan(Integer value) {
			addCriterion("ad_classify_id <", value, "adClassifyId");
			return (Criteria) this;
		}

		public Criteria andAdClassifyIdLessThanOrEqualTo(Integer value) {
			addCriterion("ad_classify_id <=", value, "adClassifyId");
			return (Criteria) this;
		}

		public Criteria andAdClassifyIdIn(List<Integer> values) {
			addCriterion("ad_classify_id in", values, "adClassifyId");
			return (Criteria) this;
		}

		public Criteria andAdClassifyIdNotIn(List<Integer> values) {
			addCriterion("ad_classify_id not in", values, "adClassifyId");
			return (Criteria) this;
		}

		public Criteria andAdClassifyIdBetween(Integer value1, Integer value2) {
			addCriterion("ad_classify_id between", value1, value2, "adClassifyId");
			return (Criteria) this;
		}

		public Criteria andAdClassifyIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ad_classify_id not between", value1, value2, "adClassifyId");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("start_time is null");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("start_time is not null");
			return (Criteria) this;
		}

		public Criteria andStartTimeEqualTo(Date value) {
			addCriterion("start_time =", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotEqualTo(Date value) {
			addCriterion("start_time <>", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThan(Date value) {
			addCriterion("start_time >", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("start_time >=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThan(Date value) {
			addCriterion("start_time <", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Date value) {
			addCriterion("start_time <=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIn(List<Date> values) {
			addCriterion("start_time in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotIn(List<Date> values) {
			addCriterion("start_time not in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeBetween(Date value1, Date value2) {
			addCriterion("start_time between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotBetween(Date value1, Date value2) {
			addCriterion("start_time not between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("end_time is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("end_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Date value) {
			addCriterion("end_time =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Date value) {
			addCriterion("end_time <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Date value) {
			addCriterion("end_time >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("end_time >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Date value) {
			addCriterion("end_time <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Date value) {
			addCriterion("end_time <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Date> values) {
			addCriterion("end_time in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Date> values) {
			addCriterion("end_time not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Date value1, Date value2) {
			addCriterion("end_time between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Date value1, Date value2) {
			addCriterion("end_time not between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andKeywordSettingIsNull() {
			addCriterion("keyword_setting is null");
			return (Criteria) this;
		}

		public Criteria andKeywordSettingIsNotNull() {
			addCriterion("keyword_setting is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordSettingEqualTo(Integer value) {
			addCriterion("keyword_setting =", value, "keywordSetting");
			return (Criteria) this;
		}

		public Criteria andKeywordSettingNotEqualTo(Integer value) {
			addCriterion("keyword_setting <>", value, "keywordSetting");
			return (Criteria) this;
		}

		public Criteria andKeywordSettingGreaterThan(Integer value) {
			addCriterion("keyword_setting >", value, "keywordSetting");
			return (Criteria) this;
		}

		public Criteria andKeywordSettingGreaterThanOrEqualTo(Integer value) {
			addCriterion("keyword_setting >=", value, "keywordSetting");
			return (Criteria) this;
		}

		public Criteria andKeywordSettingLessThan(Integer value) {
			addCriterion("keyword_setting <", value, "keywordSetting");
			return (Criteria) this;
		}

		public Criteria andKeywordSettingLessThanOrEqualTo(Integer value) {
			addCriterion("keyword_setting <=", value, "keywordSetting");
			return (Criteria) this;
		}

		public Criteria andKeywordSettingIn(List<Integer> values) {
			addCriterion("keyword_setting in", values, "keywordSetting");
			return (Criteria) this;
		}

		public Criteria andKeywordSettingNotIn(List<Integer> values) {
			addCriterion("keyword_setting not in", values, "keywordSetting");
			return (Criteria) this;
		}

		public Criteria andKeywordSettingBetween(Integer value1, Integer value2) {
			addCriterion("keyword_setting between", value1, value2, "keywordSetting");
			return (Criteria) this;
		}

		public Criteria andKeywordSettingNotBetween(Integer value1, Integer value2) {
			addCriterion("keyword_setting not between", value1, value2, "keywordSetting");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNull() {
			addCriterion("keyword is null");
			return (Criteria) this;
		}

		public Criteria andKeywordIsNotNull() {
			addCriterion("keyword is not null");
			return (Criteria) this;
		}

		public Criteria andKeywordEqualTo(String value) {
			addCriterion("keyword =", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotEqualTo(String value) {
			addCriterion("keyword <>", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThan(String value) {
			addCriterion("keyword >", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordGreaterThanOrEqualTo(String value) {
			addCriterion("keyword >=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThan(String value) {
			addCriterion("keyword <", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLessThanOrEqualTo(String value) {
			addCriterion("keyword <=", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordLike(String value) {
			addCriterion("keyword like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotLike(String value) {
			addCriterion("keyword not like", value, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordIn(List<String> values) {
			addCriterion("keyword in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotIn(List<String> values) {
			addCriterion("keyword not in", values, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordBetween(String value1, String value2) {
			addCriterion("keyword between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andKeywordNotBetween(String value1, String value2) {
			addCriterion("keyword not between", value1, value2, "keyword");
			return (Criteria) this;
		}

		public Criteria andBillingTypeIsNull() {
			addCriterion("billing_type is null");
			return (Criteria) this;
		}

		public Criteria andBillingTypeIsNotNull() {
			addCriterion("billing_type is not null");
			return (Criteria) this;
		}

		public Criteria andBillingTypeEqualTo(Integer value) {
			addCriterion("billing_type =", value, "billingType");
			return (Criteria) this;
		}

		public Criteria andBillingTypeNotEqualTo(Integer value) {
			addCriterion("billing_type <>", value, "billingType");
			return (Criteria) this;
		}

		public Criteria andBillingTypeGreaterThan(Integer value) {
			addCriterion("billing_type >", value, "billingType");
			return (Criteria) this;
		}

		public Criteria andBillingTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("billing_type >=", value, "billingType");
			return (Criteria) this;
		}

		public Criteria andBillingTypeLessThan(Integer value) {
			addCriterion("billing_type <", value, "billingType");
			return (Criteria) this;
		}

		public Criteria andBillingTypeLessThanOrEqualTo(Integer value) {
			addCriterion("billing_type <=", value, "billingType");
			return (Criteria) this;
		}

		public Criteria andBillingTypeIn(List<Integer> values) {
			addCriterion("billing_type in", values, "billingType");
			return (Criteria) this;
		}

		public Criteria andBillingTypeNotIn(List<Integer> values) {
			addCriterion("billing_type not in", values, "billingType");
			return (Criteria) this;
		}

		public Criteria andBillingTypeBetween(Integer value1, Integer value2) {
			addCriterion("billing_type between", value1, value2, "billingType");
			return (Criteria) this;
		}

		public Criteria andBillingTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("billing_type not between", value1, value2, "billingType");
			return (Criteria) this;
		}

		public Criteria andUnitPriceIsNull() {
			addCriterion("unit_price is null");
			return (Criteria) this;
		}

		public Criteria andUnitPriceIsNotNull() {
			addCriterion("unit_price is not null");
			return (Criteria) this;
		}

		public Criteria andUnitPriceEqualTo(Float value) {
			addCriterion("unit_price =", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceNotEqualTo(Float value) {
			addCriterion("unit_price <>", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceGreaterThan(Float value) {
			addCriterion("unit_price >", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceGreaterThanOrEqualTo(Float value) {
			addCriterion("unit_price >=", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceLessThan(Float value) {
			addCriterion("unit_price <", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceLessThanOrEqualTo(Float value) {
			addCriterion("unit_price <=", value, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceIn(List<Float> values) {
			addCriterion("unit_price in", values, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceNotIn(List<Float> values) {
			addCriterion("unit_price not in", values, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceBetween(Float value1, Float value2) {
			addCriterion("unit_price between", value1, value2, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andUnitPriceNotBetween(Float value1, Float value2) {
			addCriterion("unit_price not between", value1, value2, "unitPrice");
			return (Criteria) this;
		}

		public Criteria andWeightIsNull() {
			addCriterion("weight is null");
			return (Criteria) this;
		}

		public Criteria andWeightIsNotNull() {
			addCriterion("weight is not null");
			return (Criteria) this;
		}

		public Criteria andWeightEqualTo(Integer value) {
			addCriterion("weight =", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotEqualTo(Integer value) {
			addCriterion("weight <>", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThan(Integer value) {
			addCriterion("weight >", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("weight >=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThan(Integer value) {
			addCriterion("weight <", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThanOrEqualTo(Integer value) {
			addCriterion("weight <=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightIn(List<Integer> values) {
			addCriterion("weight in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotIn(List<Integer> values) {
			addCriterion("weight not in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightBetween(Integer value1, Integer value2) {
			addCriterion("weight between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotBetween(Integer value1, Integer value2) {
			addCriterion("weight not between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(String value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(String value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(String value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(String value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(String value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(String value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLike(String value) {
			addCriterion("version like", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotLike(String value) {
			addCriterion("version not like", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<String> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<String> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(String value1, String value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(String value1, String value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andMechineTypeIsNull() {
			addCriterion("mechine_type is null");
			return (Criteria) this;
		}

		public Criteria andMechineTypeIsNotNull() {
			addCriterion("mechine_type is not null");
			return (Criteria) this;
		}

		public Criteria andMechineTypeEqualTo(String value) {
			addCriterion("mechine_type =", value, "mechineType");
			return (Criteria) this;
		}

		public Criteria andMechineTypeNotEqualTo(String value) {
			addCriterion("mechine_type <>", value, "mechineType");
			return (Criteria) this;
		}

		public Criteria andMechineTypeGreaterThan(String value) {
			addCriterion("mechine_type >", value, "mechineType");
			return (Criteria) this;
		}

		public Criteria andMechineTypeGreaterThanOrEqualTo(String value) {
			addCriterion("mechine_type >=", value, "mechineType");
			return (Criteria) this;
		}

		public Criteria andMechineTypeLessThan(String value) {
			addCriterion("mechine_type <", value, "mechineType");
			return (Criteria) this;
		}

		public Criteria andMechineTypeLessThanOrEqualTo(String value) {
			addCriterion("mechine_type <=", value, "mechineType");
			return (Criteria) this;
		}

		public Criteria andMechineTypeLike(String value) {
			addCriterion("mechine_type like", value, "mechineType");
			return (Criteria) this;
		}

		public Criteria andMechineTypeNotLike(String value) {
			addCriterion("mechine_type not like", value, "mechineType");
			return (Criteria) this;
		}

		public Criteria andMechineTypeIn(List<String> values) {
			addCriterion("mechine_type in", values, "mechineType");
			return (Criteria) this;
		}

		public Criteria andMechineTypeNotIn(List<String> values) {
			addCriterion("mechine_type not in", values, "mechineType");
			return (Criteria) this;
		}

		public Criteria andMechineTypeBetween(String value1, String value2) {
			addCriterion("mechine_type between", value1, value2, "mechineType");
			return (Criteria) this;
		}

		public Criteria andMechineTypeNotBetween(String value1, String value2) {
			addCriterion("mechine_type not between", value1, value2, "mechineType");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ad_info
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ad_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}