package com.gionee.baserom.search.pojo;

public class AdKeyword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_keyword.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_keyword.keyword
     *
     * @mbggenerated
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_keyword.id
     *
     * @return the value of ad_keyword.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_keyword.id
     *
     * @param id the value for ad_keyword.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_keyword.keyword
     *
     * @return the value of ad_keyword.keyword
     *
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_keyword.keyword
     *
     * @param keyword the value for ad_keyword.keyword
     *
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }
}