package com.gionee.baserom.search.pojo;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class AdNews {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_news.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_news.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_news.img
	 * @mbggenerated
	 */
	private String img;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_news.link
	 * @mbggenerated
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_news.pos
	 * @mbggenerated
	 */
	private Integer pos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_news.enable
	 * @mbggenerated
	 */
	private Integer enable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_news.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_news.type
	 * @mbggenerated
	 */
	private Integer type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_news.id
	 * @return  the value of ad_news.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_news.id
	 * @param id  the value for ad_news.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_news.name
	 * @return  the value of ad_news.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_news.name
	 * @param name  the value for ad_news.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_news.img
	 * @return  the value of ad_news.img
	 * @mbggenerated
	 */
	public String getImg() {
		return img;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_news.img
	 * @param img  the value for ad_news.img
	 * @mbggenerated
	 */
	public void setImg(String img) {
		this.img = img == null ? null : img.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_news.link
	 * @return  the value of ad_news.link
	 * @mbggenerated
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_news.link
	 * @param link  the value for ad_news.link
	 * @mbggenerated
	 */
	public void setLink(String link) {
		this.link = link == null ? null : link.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_news.pos
	 * @return  the value of ad_news.pos
	 * @mbggenerated
	 */
	public Integer getPos() {
		return pos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_news.pos
	 * @param pos  the value for ad_news.pos
	 * @mbggenerated
	 */
	public void setPos(Integer pos) {
		this.pos = pos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_news.enable
	 * @return  the value of ad_news.enable
	 * @mbggenerated
	 */
	public Integer getEnable() {
		return enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_news.enable
	 * @param enable  the value for ad_news.enable
	 * @mbggenerated
	 */
	public void setEnable(Integer enable) {
		this.enable = enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_news.create_time
	 * @return  the value of ad_news.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_news.create_time
	 * @param createTime  the value for ad_news.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_news.type
	 * @return  the value of ad_news.type
	 * @mbggenerated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_news.type
	 * @param type  the value for ad_news.type
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}
}