package com.gionee.baserom.search.pojo;

public class AppEntrance {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_entrance.eid
	 * @mbggenerated
	 */
	private Integer eid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_entrance.entrance
	 * @mbggenerated
	 */
	private String entrance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_entrance.description
	 * @mbggenerated
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_entrance.eid
	 * @return  the value of app_entrance.eid
	 * @mbggenerated
	 */
	public Integer getEid() {
		return eid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_entrance.eid
	 * @param eid  the value for app_entrance.eid
	 * @mbggenerated
	 */
	public void setEid(Integer eid) {
		this.eid = eid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_entrance.entrance
	 * @return  the value of app_entrance.entrance
	 * @mbggenerated
	 */
	public String getEntrance() {
		return entrance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_entrance.entrance
	 * @param entrance  the value for app_entrance.entrance
	 * @mbggenerated
	 */
	public void setEntrance(String entrance) {
		this.entrance = entrance == null ? null : entrance.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_entrance.description
	 * @return  the value of app_entrance.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_entrance.description
	 * @param description  the value for app_entrance.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}