package com.gionee.baserom.search.pojo;

public class AppUri {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_uri.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_uri.uri
	 * @mbggenerated
	 */
	private String uri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_uri.type
	 * @mbggenerated
	 */
	private String type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_uri.id
	 * @return  the value of app_uri.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_uri.id
	 * @param id  the value for app_uri.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_uri.uri
	 * @return  the value of app_uri.uri
	 * @mbggenerated
	 */
	public String getUri() {
		return uri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_uri.uri
	 * @param uri  the value for app_uri.uri
	 * @mbggenerated
	 */
	public void setUri(String uri) {
		this.uri = uri == null ? null : uri.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_uri.type
	 * @return  the value of app_uri.type
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_uri.type
	 * @param type  the value for app_uri.type
	 * @mbggenerated
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}
}