package com.gionee.baserom.search.pojo;

public class AppVersionEntrance extends AppVersionEntranceKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_version_entrance.dic_id
	 * @mbggenerated
	 */
	private Integer dicId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_version_entrance.dic_id
	 * @return  the value of app_version_entrance.dic_id
	 * @mbggenerated
	 */
	public Integer getDicId() {
		return dicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_version_entrance.dic_id
	 * @param dicId  the value for app_version_entrance.dic_id
	 * @mbggenerated
	 */
	public void setDicId(Integer dicId) {
		this.dicId = dicId;
	}
}