package com.gionee.baserom.search.pojo;

public class AppVersionEntranceKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_version_entrance.app_entrance_id
	 * @mbggenerated
	 */
	private Integer appEntranceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_version_entrance.app_version_id
	 * @mbggenerated
	 */
	private Integer appVersionId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_version_entrance.app_entrance_id
	 * @return  the value of app_version_entrance.app_entrance_id
	 * @mbggenerated
	 */
	public Integer getAppEntranceId() {
		return appEntranceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_version_entrance.app_entrance_id
	 * @param appEntranceId  the value for app_version_entrance.app_entrance_id
	 * @mbggenerated
	 */
	public void setAppEntranceId(Integer appEntranceId) {
		this.appEntranceId = appEntranceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_version_entrance.app_version_id
	 * @return  the value of app_version_entrance.app_version_id
	 * @mbggenerated
	 */
	public Integer getAppVersionId() {
		return appVersionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_version_entrance.app_version_id
	 * @param appVersionId  the value for app_version_entrance.app_version_id
	 * @mbggenerated
	 */
	public void setAppVersionId(Integer appVersionId) {
		this.appVersionId = appVersionId;
	}
}