package com.gionee.baserom.search.pojo;

import java.util.List;

public class AppVersion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_version.vid
	 * @mbggenerated
	 */
	private Integer vid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_version.version
	 * @mbggenerated
	 */
	private String version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_version.description
	 * @mbggenerated
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_version.vid
	 * @return  the value of app_version.vid
	 * @mbggenerated
	 */
	public Integer getVid() {
		return vid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_version.vid
	 * @param vid  the value for app_version.vid
	 * @mbggenerated
	 */
	public void setVid(Integer vid) {
		this.vid = vid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_version.version
	 * @return  the value of app_version.version
	 * @mbggenerated
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_version.version
	 * @param version  the value for app_version.version
	 * @mbggenerated
	 */
	public void setVersion(String version) {
		this.version = version == null ? null : version.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_version.description
	 * @return  the value of app_version.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_version.description
	 * @param description  the value for app_version.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	private List<AppEntrance> entranceList;
	private List<SysDictionary> targetList;

	public List<AppEntrance> getEntranceList() {
		return entranceList;
	}

	public void setEntranceList(List<AppEntrance> entranceList) {
		this.entranceList = entranceList;
	}

	public List<SysDictionary> getTargetList() {
		return targetList;
	}

	public void setTargetList(List<SysDictionary> targetList) {
		this.targetList = targetList;
	}

}