package com.gionee.baserom.search.pojo;

import java.util.ArrayList;
import java.util.List;

public class AppVersionEntranceExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	public AppVersionEntranceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAppEntranceIdIsNull() {
			addCriterion("app_entrance_id is null");
			return (Criteria) this;
		}

		public Criteria andAppEntranceIdIsNotNull() {
			addCriterion("app_entrance_id is not null");
			return (Criteria) this;
		}

		public Criteria andAppEntranceIdEqualTo(Integer value) {
			addCriterion("app_entrance_id =", value, "appEntranceId");
			return (Criteria) this;
		}

		public Criteria andAppEntranceIdNotEqualTo(Integer value) {
			addCriterion("app_entrance_id <>", value, "appEntranceId");
			return (Criteria) this;
		}

		public Criteria andAppEntranceIdGreaterThan(Integer value) {
			addCriterion("app_entrance_id >", value, "appEntranceId");
			return (Criteria) this;
		}

		public Criteria andAppEntranceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("app_entrance_id >=", value, "appEntranceId");
			return (Criteria) this;
		}

		public Criteria andAppEntranceIdLessThan(Integer value) {
			addCriterion("app_entrance_id <", value, "appEntranceId");
			return (Criteria) this;
		}

		public Criteria andAppEntranceIdLessThanOrEqualTo(Integer value) {
			addCriterion("app_entrance_id <=", value, "appEntranceId");
			return (Criteria) this;
		}

		public Criteria andAppEntranceIdIn(List<Integer> values) {
			addCriterion("app_entrance_id in", values, "appEntranceId");
			return (Criteria) this;
		}

		public Criteria andAppEntranceIdNotIn(List<Integer> values) {
			addCriterion("app_entrance_id not in", values, "appEntranceId");
			return (Criteria) this;
		}

		public Criteria andAppEntranceIdBetween(Integer value1, Integer value2) {
			addCriterion("app_entrance_id between", value1, value2, "appEntranceId");
			return (Criteria) this;
		}

		public Criteria andAppEntranceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("app_entrance_id not between", value1, value2, "appEntranceId");
			return (Criteria) this;
		}

		public Criteria andAppVersionIdIsNull() {
			addCriterion("app_version_id is null");
			return (Criteria) this;
		}

		public Criteria andAppVersionIdIsNotNull() {
			addCriterion("app_version_id is not null");
			return (Criteria) this;
		}

		public Criteria andAppVersionIdEqualTo(Integer value) {
			addCriterion("app_version_id =", value, "appVersionId");
			return (Criteria) this;
		}

		public Criteria andAppVersionIdNotEqualTo(Integer value) {
			addCriterion("app_version_id <>", value, "appVersionId");
			return (Criteria) this;
		}

		public Criteria andAppVersionIdGreaterThan(Integer value) {
			addCriterion("app_version_id >", value, "appVersionId");
			return (Criteria) this;
		}

		public Criteria andAppVersionIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("app_version_id >=", value, "appVersionId");
			return (Criteria) this;
		}

		public Criteria andAppVersionIdLessThan(Integer value) {
			addCriterion("app_version_id <", value, "appVersionId");
			return (Criteria) this;
		}

		public Criteria andAppVersionIdLessThanOrEqualTo(Integer value) {
			addCriterion("app_version_id <=", value, "appVersionId");
			return (Criteria) this;
		}

		public Criteria andAppVersionIdIn(List<Integer> values) {
			addCriterion("app_version_id in", values, "appVersionId");
			return (Criteria) this;
		}

		public Criteria andAppVersionIdNotIn(List<Integer> values) {
			addCriterion("app_version_id not in", values, "appVersionId");
			return (Criteria) this;
		}

		public Criteria andAppVersionIdBetween(Integer value1, Integer value2) {
			addCriterion("app_version_id between", value1, value2, "appVersionId");
			return (Criteria) this;
		}

		public Criteria andAppVersionIdNotBetween(Integer value1, Integer value2) {
			addCriterion("app_version_id not between", value1, value2, "appVersionId");
			return (Criteria) this;
		}

		public Criteria andDicIdIsNull() {
			addCriterion("dic_id is null");
			return (Criteria) this;
		}

		public Criteria andDicIdIsNotNull() {
			addCriterion("dic_id is not null");
			return (Criteria) this;
		}

		public Criteria andDicIdEqualTo(Integer value) {
			addCriterion("dic_id =", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdNotEqualTo(Integer value) {
			addCriterion("dic_id <>", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdGreaterThan(Integer value) {
			addCriterion("dic_id >", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("dic_id >=", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdLessThan(Integer value) {
			addCriterion("dic_id <", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdLessThanOrEqualTo(Integer value) {
			addCriterion("dic_id <=", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdIn(List<Integer> values) {
			addCriterion("dic_id in", values, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdNotIn(List<Integer> values) {
			addCriterion("dic_id not in", values, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdBetween(Integer value1, Integer value2) {
			addCriterion("dic_id between", value1, value2, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdNotBetween(Integer value1, Integer value2) {
			addCriterion("dic_id not between", value1, value2, "dicId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table app_version_entrance
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_version_entrance
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}