package com.gionee.baserom.search.pojo;

public class Card {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card.show_enable
     *
     * @mbggenerated
     */
    private Integer showEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.id
     *
     * @return the value of card.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.id
     *
     * @param id the value for card.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.name
     *
     * @return the value of card.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.name
     *
     * @param name the value for card.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.order_id
     *
     * @return the value of card.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.order_id
     *
     * @param orderId the value for card.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card.show_enable
     *
     * @return the value of card.show_enable
     *
     * @mbggenerated
     */
    public Integer getShowEnable() {
        return showEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card.show_enable
     *
     * @param showEnable the value for card.show_enable
     *
     * @mbggenerated
     */
    public void setShowEnable(Integer showEnable) {
        this.showEnable = showEnable;
    }
}