package com.gionee.baserom.search.pojo;

public class HotkeySource {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hotkey_source.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hotkey_source.source_code
	 * @mbggenerated
	 */
	private String sourceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hotkey_source.source_name
	 * @mbggenerated
	 */
	private String sourceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hotkey_source.url
	 * @mbggenerated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hotkey_source.enable_status
	 * @mbggenerated
	 */
	private Integer enableStatus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hotkey_source.id
	 * @return  the value of hotkey_source.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hotkey_source.id
	 * @param id  the value for hotkey_source.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hotkey_source.source_code
	 * @return  the value of hotkey_source.source_code
	 * @mbggenerated
	 */
	public String getSourceCode() {
		return sourceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hotkey_source.source_code
	 * @param sourceCode  the value for hotkey_source.source_code
	 * @mbggenerated
	 */
	public void setSourceCode(String sourceCode) {
		this.sourceCode = sourceCode == null ? null : sourceCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hotkey_source.source_name
	 * @return  the value of hotkey_source.source_name
	 * @mbggenerated
	 */
	public String getSourceName() {
		return sourceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hotkey_source.source_name
	 * @param sourceName  the value for hotkey_source.source_name
	 * @mbggenerated
	 */
	public void setSourceName(String sourceName) {
		this.sourceName = sourceName == null ? null : sourceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hotkey_source.url
	 * @return  the value of hotkey_source.url
	 * @mbggenerated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hotkey_source.url
	 * @param url  the value for hotkey_source.url
	 * @mbggenerated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hotkey_source.enable_status
	 * @return  the value of hotkey_source.enable_status
	 * @mbggenerated
	 */
	public Integer getEnableStatus() {
		return enableStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hotkey_source.enable_status
	 * @param enableStatus  the value for hotkey_source.enable_status
	 * @mbggenerated
	 */
	public void setEnableStatus(Integer enableStatus) {
		this.enableStatus = enableStatus;
	}

	@Override
    public String toString() {
        return "HotkeySource [id=" + id + ", sourceCode=" + sourceCode + ", sourceName=" + sourceName + ", enableStatus="
                + enableStatus + "]";
    }
    
}