package com.gionee.baserom.search.pojo;

import java.util.Date;

public class Images {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images.type
	 * @mbggenerated
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images.file_name
	 * @mbggenerated
	 */
	private String fileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images.img_path
	 * @mbggenerated
	 */
	private String imgPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images.title
	 * @mbggenerated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images.description
	 * @mbggenerated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images.is_ref
	 * @mbggenerated
	 */
	private Integer isRef;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images.upload_date
	 * @mbggenerated
	 */
	private Date uploadDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images.id
	 * @return  the value of images.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images.id
	 * @param id  the value for images.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images.type
	 * @return  the value of images.type
	 * @mbggenerated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images.type
	 * @param type  the value for images.type
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images.file_name
	 * @return  the value of images.file_name
	 * @mbggenerated
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images.file_name
	 * @param fileName  the value for images.file_name
	 * @mbggenerated
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName == null ? null : fileName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images.img_path
	 * @return  the value of images.img_path
	 * @mbggenerated
	 */
	public String getImgPath() {
		return imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images.img_path
	 * @param imgPath  the value for images.img_path
	 * @mbggenerated
	 */
	public void setImgPath(String imgPath) {
		this.imgPath = imgPath == null ? null : imgPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images.title
	 * @return  the value of images.title
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images.title
	 * @param title  the value for images.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images.description
	 * @return  the value of images.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images.description
	 * @param description  the value for images.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images.is_ref
	 * @return  the value of images.is_ref
	 * @mbggenerated
	 */
	public Integer getIsRef() {
		return isRef;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images.is_ref
	 * @param isRef  the value for images.is_ref
	 * @mbggenerated
	 */
	public void setIsRef(Integer isRef) {
		this.isRef = isRef;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images.upload_date
	 * @return  the value of images.upload_date
	 * @mbggenerated
	 */
	public Date getUploadDate() {
		return uploadDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column images.upload_date
	 * @param uploadDate  the value for images.upload_date
	 * @mbggenerated
	 */
	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	private SysDictionary typeObj;

	public SysDictionary getTypeObj() {
		return typeObj;
	}

	public void setTypeObj(SysDictionary typeObj) {
		this.typeObj = typeObj;
	}
}