package com.gionee.baserom.search.pojo;

public class LifeService {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column life_service.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column life_service.site_name
	 * @mbggenerated
	 */
	private String siteName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column life_service.site_des
	 * @mbggenerated
	 */
	private String siteDes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column life_service.show_enable
	 * @mbggenerated
	 */
	private Integer showEnable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column life_service.sort_id
	 * @mbggenerated
	 */
	private Integer sortId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column life_service.site_url
	 * @mbggenerated
	 */
	private String siteUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column life_service.icon_url
	 * @mbggenerated
	 */
	private String iconUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column life_service.id
	 * @return  the value of life_service.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column life_service.id
	 * @param id  the value for life_service.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column life_service.site_name
	 * @return  the value of life_service.site_name
	 * @mbggenerated
	 */
	public String getSiteName() {
		return siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column life_service.site_name
	 * @param siteName  the value for life_service.site_name
	 * @mbggenerated
	 */
	public void setSiteName(String siteName) {
		this.siteName = siteName == null ? null : siteName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column life_service.site_des
	 * @return  the value of life_service.site_des
	 * @mbggenerated
	 */
	public String getSiteDes() {
		return siteDes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column life_service.site_des
	 * @param siteDes  the value for life_service.site_des
	 * @mbggenerated
	 */
	public void setSiteDes(String siteDes) {
		this.siteDes = siteDes == null ? null : siteDes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column life_service.show_enable
	 * @return  the value of life_service.show_enable
	 * @mbggenerated
	 */
	public Integer getShowEnable() {
		return showEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column life_service.show_enable
	 * @param showEnable  the value for life_service.show_enable
	 * @mbggenerated
	 */
	public void setShowEnable(Integer showEnable) {
		this.showEnable = showEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column life_service.sort_id
	 * @return  the value of life_service.sort_id
	 * @mbggenerated
	 */
	public Integer getSortId() {
		return sortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column life_service.sort_id
	 * @param sortId  the value for life_service.sort_id
	 * @mbggenerated
	 */
	public void setSortId(Integer sortId) {
		this.sortId = sortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column life_service.site_url
	 * @return  the value of life_service.site_url
	 * @mbggenerated
	 */
	public String getSiteUrl() {
		return siteUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column life_service.site_url
	 * @param siteUrl  the value for life_service.site_url
	 * @mbggenerated
	 */
	public void setSiteUrl(String siteUrl) {
		this.siteUrl = siteUrl == null ? null : siteUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column life_service.icon_url
	 * @return  the value of life_service.icon_url
	 * @mbggenerated
	 */
	public String getIconUrl() {
		return iconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column life_service.icon_url
	 * @param iconUrl  the value for life_service.icon_url
	 * @mbggenerated
	 */
	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl == null ? null : iconUrl.trim();
	}
}