package com.gionee.baserom.search.pojo;

import java.util.ArrayList;
import java.util.List;

public class ResourcesExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table resources
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table resources
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table resources
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	public ResourcesExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table resources
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andResKeyIsNull() {
			addCriterion("res_key is null");
			return (Criteria) this;
		}

		public Criteria andResKeyIsNotNull() {
			addCriterion("res_key is not null");
			return (Criteria) this;
		}

		public Criteria andResKeyEqualTo(String value) {
			addCriterion("res_key =", value, "resKey");
			return (Criteria) this;
		}

		public Criteria andResKeyNotEqualTo(String value) {
			addCriterion("res_key <>", value, "resKey");
			return (Criteria) this;
		}

		public Criteria andResKeyGreaterThan(String value) {
			addCriterion("res_key >", value, "resKey");
			return (Criteria) this;
		}

		public Criteria andResKeyGreaterThanOrEqualTo(String value) {
			addCriterion("res_key >=", value, "resKey");
			return (Criteria) this;
		}

		public Criteria andResKeyLessThan(String value) {
			addCriterion("res_key <", value, "resKey");
			return (Criteria) this;
		}

		public Criteria andResKeyLessThanOrEqualTo(String value) {
			addCriterion("res_key <=", value, "resKey");
			return (Criteria) this;
		}

		public Criteria andResKeyLike(String value) {
			addCriterion("res_key like", value, "resKey");
			return (Criteria) this;
		}

		public Criteria andResKeyNotLike(String value) {
			addCriterion("res_key not like", value, "resKey");
			return (Criteria) this;
		}

		public Criteria andResKeyIn(List<String> values) {
			addCriterion("res_key in", values, "resKey");
			return (Criteria) this;
		}

		public Criteria andResKeyNotIn(List<String> values) {
			addCriterion("res_key not in", values, "resKey");
			return (Criteria) this;
		}

		public Criteria andResKeyBetween(String value1, String value2) {
			addCriterion("res_key between", value1, value2, "resKey");
			return (Criteria) this;
		}

		public Criteria andResKeyNotBetween(String value1, String value2) {
			addCriterion("res_key not between", value1, value2, "resKey");
			return (Criteria) this;
		}

		public Criteria andResUrlIsNull() {
			addCriterion("res_url is null");
			return (Criteria) this;
		}

		public Criteria andResUrlIsNotNull() {
			addCriterion("res_url is not null");
			return (Criteria) this;
		}

		public Criteria andResUrlEqualTo(String value) {
			addCriterion("res_url =", value, "resUrl");
			return (Criteria) this;
		}

		public Criteria andResUrlNotEqualTo(String value) {
			addCriterion("res_url <>", value, "resUrl");
			return (Criteria) this;
		}

		public Criteria andResUrlGreaterThan(String value) {
			addCriterion("res_url >", value, "resUrl");
			return (Criteria) this;
		}

		public Criteria andResUrlGreaterThanOrEqualTo(String value) {
			addCriterion("res_url >=", value, "resUrl");
			return (Criteria) this;
		}

		public Criteria andResUrlLessThan(String value) {
			addCriterion("res_url <", value, "resUrl");
			return (Criteria) this;
		}

		public Criteria andResUrlLessThanOrEqualTo(String value) {
			addCriterion("res_url <=", value, "resUrl");
			return (Criteria) this;
		}

		public Criteria andResUrlLike(String value) {
			addCriterion("res_url like", value, "resUrl");
			return (Criteria) this;
		}

		public Criteria andResUrlNotLike(String value) {
			addCriterion("res_url not like", value, "resUrl");
			return (Criteria) this;
		}

		public Criteria andResUrlIn(List<String> values) {
			addCriterion("res_url in", values, "resUrl");
			return (Criteria) this;
		}

		public Criteria andResUrlNotIn(List<String> values) {
			addCriterion("res_url not in", values, "resUrl");
			return (Criteria) this;
		}

		public Criteria andResUrlBetween(String value1, String value2) {
			addCriterion("res_url between", value1, value2, "resUrl");
			return (Criteria) this;
		}

		public Criteria andResUrlNotBetween(String value1, String value2) {
			addCriterion("res_url not between", value1, value2, "resUrl");
			return (Criteria) this;
		}

		public Criteria andIconIsNull() {
			addCriterion("icon is null");
			return (Criteria) this;
		}

		public Criteria andIconIsNotNull() {
			addCriterion("icon is not null");
			return (Criteria) this;
		}

		public Criteria andIconEqualTo(String value) {
			addCriterion("icon =", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotEqualTo(String value) {
			addCriterion("icon <>", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconGreaterThan(String value) {
			addCriterion("icon >", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconGreaterThanOrEqualTo(String value) {
			addCriterion("icon >=", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconLessThan(String value) {
			addCriterion("icon <", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconLessThanOrEqualTo(String value) {
			addCriterion("icon <=", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconLike(String value) {
			addCriterion("icon like", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotLike(String value) {
			addCriterion("icon not like", value, "icon");
			return (Criteria) this;
		}

		public Criteria andIconIn(List<String> values) {
			addCriterion("icon in", values, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotIn(List<String> values) {
			addCriterion("icon not in", values, "icon");
			return (Criteria) this;
		}

		public Criteria andIconBetween(String value1, String value2) {
			addCriterion("icon between", value1, value2, "icon");
			return (Criteria) this;
		}

		public Criteria andIconNotBetween(String value1, String value2) {
			addCriterion("icon not between", value1, value2, "icon");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNull() {
			addCriterion("parent_id is null");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNotNull() {
			addCriterion("parent_id is not null");
			return (Criteria) this;
		}

		public Criteria andParentIdEqualTo(Integer value) {
			addCriterion("parent_id =", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotEqualTo(Integer value) {
			addCriterion("parent_id <>", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThan(Integer value) {
			addCriterion("parent_id >", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("parent_id >=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThan(Integer value) {
			addCriterion("parent_id <", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThanOrEqualTo(Integer value) {
			addCriterion("parent_id <=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdIn(List<Integer> values) {
			addCriterion("parent_id in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotIn(List<Integer> values) {
			addCriterion("parent_id not in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdBetween(Integer value1, Integer value2) {
			addCriterion("parent_id between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotBetween(Integer value1, Integer value2) {
			addCriterion("parent_id not between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdListIsNull() {
			addCriterion("parent_id_list is null");
			return (Criteria) this;
		}

		public Criteria andParentIdListIsNotNull() {
			addCriterion("parent_id_list is not null");
			return (Criteria) this;
		}

		public Criteria andParentIdListEqualTo(String value) {
			addCriterion("parent_id_list =", value, "parentIdList");
			return (Criteria) this;
		}

		public Criteria andParentIdListNotEqualTo(String value) {
			addCriterion("parent_id_list <>", value, "parentIdList");
			return (Criteria) this;
		}

		public Criteria andParentIdListGreaterThan(String value) {
			addCriterion("parent_id_list >", value, "parentIdList");
			return (Criteria) this;
		}

		public Criteria andParentIdListGreaterThanOrEqualTo(String value) {
			addCriterion("parent_id_list >=", value, "parentIdList");
			return (Criteria) this;
		}

		public Criteria andParentIdListLessThan(String value) {
			addCriterion("parent_id_list <", value, "parentIdList");
			return (Criteria) this;
		}

		public Criteria andParentIdListLessThanOrEqualTo(String value) {
			addCriterion("parent_id_list <=", value, "parentIdList");
			return (Criteria) this;
		}

		public Criteria andParentIdListLike(String value) {
			addCriterion("parent_id_list like", value, "parentIdList");
			return (Criteria) this;
		}

		public Criteria andParentIdListNotLike(String value) {
			addCriterion("parent_id_list not like", value, "parentIdList");
			return (Criteria) this;
		}

		public Criteria andParentIdListIn(List<String> values) {
			addCriterion("parent_id_list in", values, "parentIdList");
			return (Criteria) this;
		}

		public Criteria andParentIdListNotIn(List<String> values) {
			addCriterion("parent_id_list not in", values, "parentIdList");
			return (Criteria) this;
		}

		public Criteria andParentIdListBetween(String value1, String value2) {
			addCriterion("parent_id_list between", value1, value2, "parentIdList");
			return (Criteria) this;
		}

		public Criteria andParentIdListNotBetween(String value1, String value2) {
			addCriterion("parent_id_list not between", value1, value2, "parentIdList");
			return (Criteria) this;
		}

		public Criteria andLevelIsNull() {
			addCriterion("level is null");
			return (Criteria) this;
		}

		public Criteria andLevelIsNotNull() {
			addCriterion("level is not null");
			return (Criteria) this;
		}

		public Criteria andLevelEqualTo(Integer value) {
			addCriterion("level =", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotEqualTo(Integer value) {
			addCriterion("level <>", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThan(Integer value) {
			addCriterion("level >", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("level >=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThan(Integer value) {
			addCriterion("level <", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThanOrEqualTo(Integer value) {
			addCriterion("level <=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelIn(List<Integer> values) {
			addCriterion("level in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotIn(List<Integer> values) {
			addCriterion("level not in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelBetween(Integer value1, Integer value2) {
			addCriterion("level between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("level not between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andCssClassIsNull() {
			addCriterion("css_class is null");
			return (Criteria) this;
		}

		public Criteria andCssClassIsNotNull() {
			addCriterion("css_class is not null");
			return (Criteria) this;
		}

		public Criteria andCssClassEqualTo(String value) {
			addCriterion("css_class =", value, "cssClass");
			return (Criteria) this;
		}

		public Criteria andCssClassNotEqualTo(String value) {
			addCriterion("css_class <>", value, "cssClass");
			return (Criteria) this;
		}

		public Criteria andCssClassGreaterThan(String value) {
			addCriterion("css_class >", value, "cssClass");
			return (Criteria) this;
		}

		public Criteria andCssClassGreaterThanOrEqualTo(String value) {
			addCriterion("css_class >=", value, "cssClass");
			return (Criteria) this;
		}

		public Criteria andCssClassLessThan(String value) {
			addCriterion("css_class <", value, "cssClass");
			return (Criteria) this;
		}

		public Criteria andCssClassLessThanOrEqualTo(String value) {
			addCriterion("css_class <=", value, "cssClass");
			return (Criteria) this;
		}

		public Criteria andCssClassLike(String value) {
			addCriterion("css_class like", value, "cssClass");
			return (Criteria) this;
		}

		public Criteria andCssClassNotLike(String value) {
			addCriterion("css_class not like", value, "cssClass");
			return (Criteria) this;
		}

		public Criteria andCssClassIn(List<String> values) {
			addCriterion("css_class in", values, "cssClass");
			return (Criteria) this;
		}

		public Criteria andCssClassNotIn(List<String> values) {
			addCriterion("css_class not in", values, "cssClass");
			return (Criteria) this;
		}

		public Criteria andCssClassBetween(String value1, String value2) {
			addCriterion("css_class between", value1, value2, "cssClass");
			return (Criteria) this;
		}

		public Criteria andCssClassNotBetween(String value1, String value2) {
			addCriterion("css_class not between", value1, value2, "cssClass");
			return (Criteria) this;
		}

		public Criteria andTargetIsNull() {
			addCriterion("target is null");
			return (Criteria) this;
		}

		public Criteria andTargetIsNotNull() {
			addCriterion("target is not null");
			return (Criteria) this;
		}

		public Criteria andTargetEqualTo(String value) {
			addCriterion("target =", value, "target");
			return (Criteria) this;
		}

		public Criteria andTargetNotEqualTo(String value) {
			addCriterion("target <>", value, "target");
			return (Criteria) this;
		}

		public Criteria andTargetGreaterThan(String value) {
			addCriterion("target >", value, "target");
			return (Criteria) this;
		}

		public Criteria andTargetGreaterThanOrEqualTo(String value) {
			addCriterion("target >=", value, "target");
			return (Criteria) this;
		}

		public Criteria andTargetLessThan(String value) {
			addCriterion("target <", value, "target");
			return (Criteria) this;
		}

		public Criteria andTargetLessThanOrEqualTo(String value) {
			addCriterion("target <=", value, "target");
			return (Criteria) this;
		}

		public Criteria andTargetLike(String value) {
			addCriterion("target like", value, "target");
			return (Criteria) this;
		}

		public Criteria andTargetNotLike(String value) {
			addCriterion("target not like", value, "target");
			return (Criteria) this;
		}

		public Criteria andTargetIn(List<String> values) {
			addCriterion("target in", values, "target");
			return (Criteria) this;
		}

		public Criteria andTargetNotIn(List<String> values) {
			addCriterion("target not in", values, "target");
			return (Criteria) this;
		}

		public Criteria andTargetBetween(String value1, String value2) {
			addCriterion("target between", value1, value2, "target");
			return (Criteria) this;
		}

		public Criteria andTargetNotBetween(String value1, String value2) {
			addCriterion("target not between", value1, value2, "target");
			return (Criteria) this;
		}

		public Criteria andWinWidthIsNull() {
			addCriterion("win_width is null");
			return (Criteria) this;
		}

		public Criteria andWinWidthIsNotNull() {
			addCriterion("win_width is not null");
			return (Criteria) this;
		}

		public Criteria andWinWidthEqualTo(Integer value) {
			addCriterion("win_width =", value, "winWidth");
			return (Criteria) this;
		}

		public Criteria andWinWidthNotEqualTo(Integer value) {
			addCriterion("win_width <>", value, "winWidth");
			return (Criteria) this;
		}

		public Criteria andWinWidthGreaterThan(Integer value) {
			addCriterion("win_width >", value, "winWidth");
			return (Criteria) this;
		}

		public Criteria andWinWidthGreaterThanOrEqualTo(Integer value) {
			addCriterion("win_width >=", value, "winWidth");
			return (Criteria) this;
		}

		public Criteria andWinWidthLessThan(Integer value) {
			addCriterion("win_width <", value, "winWidth");
			return (Criteria) this;
		}

		public Criteria andWinWidthLessThanOrEqualTo(Integer value) {
			addCriterion("win_width <=", value, "winWidth");
			return (Criteria) this;
		}

		public Criteria andWinWidthIn(List<Integer> values) {
			addCriterion("win_width in", values, "winWidth");
			return (Criteria) this;
		}

		public Criteria andWinWidthNotIn(List<Integer> values) {
			addCriterion("win_width not in", values, "winWidth");
			return (Criteria) this;
		}

		public Criteria andWinWidthBetween(Integer value1, Integer value2) {
			addCriterion("win_width between", value1, value2, "winWidth");
			return (Criteria) this;
		}

		public Criteria andWinWidthNotBetween(Integer value1, Integer value2) {
			addCriterion("win_width not between", value1, value2, "winWidth");
			return (Criteria) this;
		}

		public Criteria andWinHeightIsNull() {
			addCriterion("win_height is null");
			return (Criteria) this;
		}

		public Criteria andWinHeightIsNotNull() {
			addCriterion("win_height is not null");
			return (Criteria) this;
		}

		public Criteria andWinHeightEqualTo(Integer value) {
			addCriterion("win_height =", value, "winHeight");
			return (Criteria) this;
		}

		public Criteria andWinHeightNotEqualTo(Integer value) {
			addCriterion("win_height <>", value, "winHeight");
			return (Criteria) this;
		}

		public Criteria andWinHeightGreaterThan(Integer value) {
			addCriterion("win_height >", value, "winHeight");
			return (Criteria) this;
		}

		public Criteria andWinHeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("win_height >=", value, "winHeight");
			return (Criteria) this;
		}

		public Criteria andWinHeightLessThan(Integer value) {
			addCriterion("win_height <", value, "winHeight");
			return (Criteria) this;
		}

		public Criteria andWinHeightLessThanOrEqualTo(Integer value) {
			addCriterion("win_height <=", value, "winHeight");
			return (Criteria) this;
		}

		public Criteria andWinHeightIn(List<Integer> values) {
			addCriterion("win_height in", values, "winHeight");
			return (Criteria) this;
		}

		public Criteria andWinHeightNotIn(List<Integer> values) {
			addCriterion("win_height not in", values, "winHeight");
			return (Criteria) this;
		}

		public Criteria andWinHeightBetween(Integer value1, Integer value2) {
			addCriterion("win_height between", value1, value2, "winHeight");
			return (Criteria) this;
		}

		public Criteria andWinHeightNotBetween(Integer value1, Integer value2) {
			addCriterion("win_height not between", value1, value2, "winHeight");
			return (Criteria) this;
		}

		public Criteria andWarnIsNull() {
			addCriterion("warn is null");
			return (Criteria) this;
		}

		public Criteria andWarnIsNotNull() {
			addCriterion("warn is not null");
			return (Criteria) this;
		}

		public Criteria andWarnEqualTo(String value) {
			addCriterion("warn =", value, "warn");
			return (Criteria) this;
		}

		public Criteria andWarnNotEqualTo(String value) {
			addCriterion("warn <>", value, "warn");
			return (Criteria) this;
		}

		public Criteria andWarnGreaterThan(String value) {
			addCriterion("warn >", value, "warn");
			return (Criteria) this;
		}

		public Criteria andWarnGreaterThanOrEqualTo(String value) {
			addCriterion("warn >=", value, "warn");
			return (Criteria) this;
		}

		public Criteria andWarnLessThan(String value) {
			addCriterion("warn <", value, "warn");
			return (Criteria) this;
		}

		public Criteria andWarnLessThanOrEqualTo(String value) {
			addCriterion("warn <=", value, "warn");
			return (Criteria) this;
		}

		public Criteria andWarnLike(String value) {
			addCriterion("warn like", value, "warn");
			return (Criteria) this;
		}

		public Criteria andWarnNotLike(String value) {
			addCriterion("warn not like", value, "warn");
			return (Criteria) this;
		}

		public Criteria andWarnIn(List<String> values) {
			addCriterion("warn in", values, "warn");
			return (Criteria) this;
		}

		public Criteria andWarnNotIn(List<String> values) {
			addCriterion("warn not in", values, "warn");
			return (Criteria) this;
		}

		public Criteria andWarnBetween(String value1, String value2) {
			addCriterion("warn between", value1, value2, "warn");
			return (Criteria) this;
		}

		public Criteria andWarnNotBetween(String value1, String value2) {
			addCriterion("warn not between", value1, value2, "warn");
			return (Criteria) this;
		}

		public Criteria andTittleIsNull() {
			addCriterion("tittle is null");
			return (Criteria) this;
		}

		public Criteria andTittleIsNotNull() {
			addCriterion("tittle is not null");
			return (Criteria) this;
		}

		public Criteria andTittleEqualTo(String value) {
			addCriterion("tittle =", value, "tittle");
			return (Criteria) this;
		}

		public Criteria andTittleNotEqualTo(String value) {
			addCriterion("tittle <>", value, "tittle");
			return (Criteria) this;
		}

		public Criteria andTittleGreaterThan(String value) {
			addCriterion("tittle >", value, "tittle");
			return (Criteria) this;
		}

		public Criteria andTittleGreaterThanOrEqualTo(String value) {
			addCriterion("tittle >=", value, "tittle");
			return (Criteria) this;
		}

		public Criteria andTittleLessThan(String value) {
			addCriterion("tittle <", value, "tittle");
			return (Criteria) this;
		}

		public Criteria andTittleLessThanOrEqualTo(String value) {
			addCriterion("tittle <=", value, "tittle");
			return (Criteria) this;
		}

		public Criteria andTittleLike(String value) {
			addCriterion("tittle like", value, "tittle");
			return (Criteria) this;
		}

		public Criteria andTittleNotLike(String value) {
			addCriterion("tittle not like", value, "tittle");
			return (Criteria) this;
		}

		public Criteria andTittleIn(List<String> values) {
			addCriterion("tittle in", values, "tittle");
			return (Criteria) this;
		}

		public Criteria andTittleNotIn(List<String> values) {
			addCriterion("tittle not in", values, "tittle");
			return (Criteria) this;
		}

		public Criteria andTittleBetween(String value1, String value2) {
			addCriterion("tittle between", value1, value2, "tittle");
			return (Criteria) this;
		}

		public Criteria andTittleNotBetween(String value1, String value2) {
			addCriterion("tittle not between", value1, value2, "tittle");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table resources
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resources
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}