package com.gionee.baserom.search.pojo;

public class Resources {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.res_key
	 * @mbggenerated
	 */
	private String resKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.res_url
	 * @mbggenerated
	 */
	private String resUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.icon
	 * @mbggenerated
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.type
	 * @mbggenerated
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.parent_id
	 * @mbggenerated
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.parent_id_list
	 * @mbggenerated
	 */
	private String parentIdList;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.level
	 * @mbggenerated
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.description
	 * @mbggenerated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.css_class
	 * @mbggenerated
	 */
	private String cssClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.target
	 * @mbggenerated
	 */
	private String target;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.win_width
	 * @mbggenerated
	 */
	private Integer winWidth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.win_height
	 * @mbggenerated
	 */
	private Integer winHeight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.warn
	 * @mbggenerated
	 */
	private String warn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.tittle
	 * @mbggenerated
	 */
	private String tittle;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.id
	 * @return  the value of resources.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.id
	 * @param id  the value for resources.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.name
	 * @return  the value of resources.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.name
	 * @param name  the value for resources.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.res_key
	 * @return  the value of resources.res_key
	 * @mbggenerated
	 */
	public String getResKey() {
		return resKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.res_key
	 * @param resKey  the value for resources.res_key
	 * @mbggenerated
	 */
	public void setResKey(String resKey) {
		this.resKey = resKey == null ? null : resKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.res_url
	 * @return  the value of resources.res_url
	 * @mbggenerated
	 */
	public String getResUrl() {
		return resUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.res_url
	 * @param resUrl  the value for resources.res_url
	 * @mbggenerated
	 */
	public void setResUrl(String resUrl) {
		this.resUrl = resUrl == null ? null : resUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.icon
	 * @return  the value of resources.icon
	 * @mbggenerated
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.icon
	 * @param icon  the value for resources.icon
	 * @mbggenerated
	 */
	public void setIcon(String icon) {
		this.icon = icon == null ? null : icon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.type
	 * @return  the value of resources.type
	 * @mbggenerated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.type
	 * @param type  the value for resources.type
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.parent_id
	 * @return  the value of resources.parent_id
	 * @mbggenerated
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.parent_id
	 * @param parentId  the value for resources.parent_id
	 * @mbggenerated
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.parent_id_list
	 * @return  the value of resources.parent_id_list
	 * @mbggenerated
	 */
	public String getParentIdList() {
		return parentIdList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.parent_id_list
	 * @param parentIdList  the value for resources.parent_id_list
	 * @mbggenerated
	 */
	public void setParentIdList(String parentIdList) {
		this.parentIdList = parentIdList == null ? null : parentIdList.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.level
	 * @return  the value of resources.level
	 * @mbggenerated
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.level
	 * @param level  the value for resources.level
	 * @mbggenerated
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.description
	 * @return  the value of resources.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.description
	 * @param description  the value for resources.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.css_class
	 * @return  the value of resources.css_class
	 * @mbggenerated
	 */
	public String getCssClass() {
		return cssClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.css_class
	 * @param cssClass  the value for resources.css_class
	 * @mbggenerated
	 */
	public void setCssClass(String cssClass) {
		this.cssClass = cssClass == null ? null : cssClass.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.target
	 * @return  the value of resources.target
	 * @mbggenerated
	 */
	public String getTarget() {
		return target;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.target
	 * @param target  the value for resources.target
	 * @mbggenerated
	 */
	public void setTarget(String target) {
		this.target = target == null ? null : target.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.win_width
	 * @return  the value of resources.win_width
	 * @mbggenerated
	 */
	public Integer getWinWidth() {
		return winWidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.win_width
	 * @param winWidth  the value for resources.win_width
	 * @mbggenerated
	 */
	public void setWinWidth(Integer winWidth) {
		this.winWidth = winWidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.win_height
	 * @return  the value of resources.win_height
	 * @mbggenerated
	 */
	public Integer getWinHeight() {
		return winHeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.win_height
	 * @param winHeight  the value for resources.win_height
	 * @mbggenerated
	 */
	public void setWinHeight(Integer winHeight) {
		this.winHeight = winHeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.warn
	 * @return  the value of resources.warn
	 * @mbggenerated
	 */
	public String getWarn() {
		return warn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.warn
	 * @param warn  the value for resources.warn
	 * @mbggenerated
	 */
	public void setWarn(String warn) {
		this.warn = warn == null ? null : warn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.tittle
	 * @return  the value of resources.tittle
	 * @mbggenerated
	 */
	public String getTittle() {
		return tittle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.tittle
	 * @param tittle  the value for resources.tittle
	 * @mbggenerated
	 */
	public void setTittle(String tittle) {
		this.tittle = tittle == null ? null : tittle.trim();
	}
}