package com.gionee.baserom.search.pojo;

public class Rosters {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rosters.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rosters.usertype
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rosters.packagename
     *
     * @mbggenerated
     */
    private String packagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rosters.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rosters.id
     *
     * @return the value of rosters.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rosters.id
     *
     * @param id the value for rosters.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rosters.usertype
     *
     * @return the value of rosters.usertype
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rosters.usertype
     *
     * @param usertype the value for rosters.usertype
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rosters.packagename
     *
     * @return the value of rosters.packagename
     *
     * @mbggenerated
     */
    public String getPackagename() {
        return packagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rosters.packagename
     *
     * @param packagename the value for rosters.packagename
     *
     * @mbggenerated
     */
    public void setPackagename(String packagename) {
        this.packagename = packagename == null ? null : packagename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rosters.status
     *
     * @return the value of rosters.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rosters.status
     *
     * @param status the value for rosters.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}