package com.gionee.baserom.search.pojo;

public class SiteNavigation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_navigation.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_navigation.site_name
	 * @mbggenerated
	 */
	private String siteName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_navigation.site_url
	 * @mbggenerated
	 */
	private String siteUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_navigation.sort_id
	 * @mbggenerated
	 */
	private Integer sortId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_navigation.show_enable
	 * @mbggenerated
	 */
	private Integer showEnable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_navigation.icon_url
	 * @mbggenerated
	 */
	private String iconUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_navigation.type
	 * @mbggenerated
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column site_navigation.icon
	 * @mbggenerated
	 */
	private byte[] icon;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_navigation.id
	 * @return  the value of site_navigation.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_navigation.id
	 * @param id  the value for site_navigation.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_navigation.site_name
	 * @return  the value of site_navigation.site_name
	 * @mbggenerated
	 */
	public String getSiteName() {
		return siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_navigation.site_name
	 * @param siteName  the value for site_navigation.site_name
	 * @mbggenerated
	 */
	public void setSiteName(String siteName) {
		this.siteName = siteName == null ? null : siteName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_navigation.site_url
	 * @return  the value of site_navigation.site_url
	 * @mbggenerated
	 */
	public String getSiteUrl() {
		return siteUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_navigation.site_url
	 * @param siteUrl  the value for site_navigation.site_url
	 * @mbggenerated
	 */
	public void setSiteUrl(String siteUrl) {
		this.siteUrl = siteUrl == null ? null : siteUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_navigation.sort_id
	 * @return  the value of site_navigation.sort_id
	 * @mbggenerated
	 */
	public Integer getSortId() {
		return sortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_navigation.sort_id
	 * @param sortId  the value for site_navigation.sort_id
	 * @mbggenerated
	 */
	public void setSortId(Integer sortId) {
		this.sortId = sortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_navigation.show_enable
	 * @return  the value of site_navigation.show_enable
	 * @mbggenerated
	 */
	public Integer getShowEnable() {
		return showEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_navigation.show_enable
	 * @param showEnable  the value for site_navigation.show_enable
	 * @mbggenerated
	 */
	public void setShowEnable(Integer showEnable) {
		this.showEnable = showEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_navigation.icon_url
	 * @return  the value of site_navigation.icon_url
	 * @mbggenerated
	 */
	public String getIconUrl() {
		return iconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_navigation.icon_url
	 * @param iconUrl  the value for site_navigation.icon_url
	 * @mbggenerated
	 */
	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl == null ? null : iconUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_navigation.type
	 * @return  the value of site_navigation.type
	 * @mbggenerated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_navigation.type
	 * @param type  the value for site_navigation.type
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column site_navigation.icon
	 * @return  the value of site_navigation.icon
	 * @mbggenerated
	 */
	public byte[] getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column site_navigation.icon
	 * @param icon  the value for site_navigation.icon
	 * @mbggenerated
	 */
	public void setIcon(byte[] icon) {
		this.icon = icon;
	}
}