package com.gionee.baserom.search.pojo;

import java.util.ArrayList;
import java.util.List;

public class SiteNavigationExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	public SiteNavigationExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andDicIdIsNull() {
			addCriterion("dic_id is null");
			return (Criteria) this;
		}

		public Criteria andDicIdIsNotNull() {
			addCriterion("dic_id is not null");
			return (Criteria) this;
		}

		public Criteria andDicIdEqualTo(Integer value) {
			addCriterion("dic_id =", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdNotEqualTo(Integer value) {
			addCriterion("dic_id <>", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdGreaterThan(Integer value) {
			addCriterion("dic_id >", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("dic_id >=", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdLessThan(Integer value) {
			addCriterion("dic_id <", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdLessThanOrEqualTo(Integer value) {
			addCriterion("dic_id <=", value, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdIn(List<Integer> values) {
			addCriterion("dic_id in", values, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdNotIn(List<Integer> values) {
			addCriterion("dic_id not in", values, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdBetween(Integer value1, Integer value2) {
			addCriterion("dic_id between", value1, value2, "dicId");
			return (Criteria) this;
		}

		public Criteria andDicIdNotBetween(Integer value1, Integer value2) {
			addCriterion("dic_id not between", value1, value2, "dicId");
			return (Criteria) this;
		}

		public Criteria andSiteNameIsNull() {
			addCriterion("site_name is null");
			return (Criteria) this;
		}

		public Criteria andSiteNameIsNotNull() {
			addCriterion("site_name is not null");
			return (Criteria) this;
		}

		public Criteria andSiteNameEqualTo(String value) {
			addCriterion("site_name =", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotEqualTo(String value) {
			addCriterion("site_name <>", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameGreaterThan(String value) {
			addCriterion("site_name >", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameGreaterThanOrEqualTo(String value) {
			addCriterion("site_name >=", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLessThan(String value) {
			addCriterion("site_name <", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLessThanOrEqualTo(String value) {
			addCriterion("site_name <=", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameLike(String value) {
			addCriterion("site_name like", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotLike(String value) {
			addCriterion("site_name not like", value, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameIn(List<String> values) {
			addCriterion("site_name in", values, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotIn(List<String> values) {
			addCriterion("site_name not in", values, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameBetween(String value1, String value2) {
			addCriterion("site_name between", value1, value2, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteNameNotBetween(String value1, String value2) {
			addCriterion("site_name not between", value1, value2, "siteName");
			return (Criteria) this;
		}

		public Criteria andSiteUrlIsNull() {
			addCriterion("site_url is null");
			return (Criteria) this;
		}

		public Criteria andSiteUrlIsNotNull() {
			addCriterion("site_url is not null");
			return (Criteria) this;
		}

		public Criteria andSiteUrlEqualTo(String value) {
			addCriterion("site_url =", value, "siteUrl");
			return (Criteria) this;
		}

		public Criteria andSiteUrlNotEqualTo(String value) {
			addCriterion("site_url <>", value, "siteUrl");
			return (Criteria) this;
		}

		public Criteria andSiteUrlGreaterThan(String value) {
			addCriterion("site_url >", value, "siteUrl");
			return (Criteria) this;
		}

		public Criteria andSiteUrlGreaterThanOrEqualTo(String value) {
			addCriterion("site_url >=", value, "siteUrl");
			return (Criteria) this;
		}

		public Criteria andSiteUrlLessThan(String value) {
			addCriterion("site_url <", value, "siteUrl");
			return (Criteria) this;
		}

		public Criteria andSiteUrlLessThanOrEqualTo(String value) {
			addCriterion("site_url <=", value, "siteUrl");
			return (Criteria) this;
		}

		public Criteria andSiteUrlLike(String value) {
			addCriterion("site_url like", value, "siteUrl");
			return (Criteria) this;
		}

		public Criteria andSiteUrlNotLike(String value) {
			addCriterion("site_url not like", value, "siteUrl");
			return (Criteria) this;
		}

		public Criteria andSiteUrlIn(List<String> values) {
			addCriterion("site_url in", values, "siteUrl");
			return (Criteria) this;
		}

		public Criteria andSiteUrlNotIn(List<String> values) {
			addCriterion("site_url not in", values, "siteUrl");
			return (Criteria) this;
		}

		public Criteria andSiteUrlBetween(String value1, String value2) {
			addCriterion("site_url between", value1, value2, "siteUrl");
			return (Criteria) this;
		}

		public Criteria andSiteUrlNotBetween(String value1, String value2) {
			addCriterion("site_url not between", value1, value2, "siteUrl");
			return (Criteria) this;
		}

		public Criteria andSortIdIsNull() {
			addCriterion("sort_id is null");
			return (Criteria) this;
		}

		public Criteria andSortIdIsNotNull() {
			addCriterion("sort_id is not null");
			return (Criteria) this;
		}

		public Criteria andSortIdEqualTo(Integer value) {
			addCriterion("sort_id =", value, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdNotEqualTo(Integer value) {
			addCriterion("sort_id <>", value, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdGreaterThan(Integer value) {
			addCriterion("sort_id >", value, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("sort_id >=", value, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdLessThan(Integer value) {
			addCriterion("sort_id <", value, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdLessThanOrEqualTo(Integer value) {
			addCriterion("sort_id <=", value, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdIn(List<Integer> values) {
			addCriterion("sort_id in", values, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdNotIn(List<Integer> values) {
			addCriterion("sort_id not in", values, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdBetween(Integer value1, Integer value2) {
			addCriterion("sort_id between", value1, value2, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdNotBetween(Integer value1, Integer value2) {
			addCriterion("sort_id not between", value1, value2, "sortId");
			return (Criteria) this;
		}

		public Criteria andShowEnableIsNull() {
			addCriterion("show_enable is null");
			return (Criteria) this;
		}

		public Criteria andShowEnableIsNotNull() {
			addCriterion("show_enable is not null");
			return (Criteria) this;
		}

		public Criteria andShowEnableEqualTo(Integer value) {
			addCriterion("show_enable =", value, "showEnable");
			return (Criteria) this;
		}

		public Criteria andShowEnableNotEqualTo(Integer value) {
			addCriterion("show_enable <>", value, "showEnable");
			return (Criteria) this;
		}

		public Criteria andShowEnableGreaterThan(Integer value) {
			addCriterion("show_enable >", value, "showEnable");
			return (Criteria) this;
		}

		public Criteria andShowEnableGreaterThanOrEqualTo(Integer value) {
			addCriterion("show_enable >=", value, "showEnable");
			return (Criteria) this;
		}

		public Criteria andShowEnableLessThan(Integer value) {
			addCriterion("show_enable <", value, "showEnable");
			return (Criteria) this;
		}

		public Criteria andShowEnableLessThanOrEqualTo(Integer value) {
			addCriterion("show_enable <=", value, "showEnable");
			return (Criteria) this;
		}

		public Criteria andShowEnableIn(List<Integer> values) {
			addCriterion("show_enable in", values, "showEnable");
			return (Criteria) this;
		}

		public Criteria andShowEnableNotIn(List<Integer> values) {
			addCriterion("show_enable not in", values, "showEnable");
			return (Criteria) this;
		}

		public Criteria andShowEnableBetween(Integer value1, Integer value2) {
			addCriterion("show_enable between", value1, value2, "showEnable");
			return (Criteria) this;
		}

		public Criteria andShowEnableNotBetween(Integer value1, Integer value2) {
			addCriterion("show_enable not between", value1, value2, "showEnable");
			return (Criteria) this;
		}

		public Criteria andIconUrlIsNull() {
			addCriterion("icon_url is null");
			return (Criteria) this;
		}

		public Criteria andIconUrlIsNotNull() {
			addCriterion("icon_url is not null");
			return (Criteria) this;
		}

		public Criteria andIconUrlEqualTo(String value) {
			addCriterion("icon_url =", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlNotEqualTo(String value) {
			addCriterion("icon_url <>", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlGreaterThan(String value) {
			addCriterion("icon_url >", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlGreaterThanOrEqualTo(String value) {
			addCriterion("icon_url >=", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlLessThan(String value) {
			addCriterion("icon_url <", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlLessThanOrEqualTo(String value) {
			addCriterion("icon_url <=", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlLike(String value) {
			addCriterion("icon_url like", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlNotLike(String value) {
			addCriterion("icon_url not like", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlIn(List<String> values) {
			addCriterion("icon_url in", values, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlNotIn(List<String> values) {
			addCriterion("icon_url not in", values, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlBetween(String value1, String value2) {
			addCriterion("icon_url between", value1, value2, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlNotBetween(String value1, String value2) {
			addCriterion("icon_url not between", value1, value2, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table site_navigation
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table site_navigation
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}