package com.gionee.baserom.search.pojo;

import java.util.List;

public class SysDictionaryClassify {
	
	private List<SysDictionary> sysDicList;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_classify.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_classify.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary_classify.dic_key
     *
     * @mbggenerated
     */
    private String dicKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_classify.id
     *
     * @return the value of sys_dictionary_classify.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_classify.id
     *
     * @param id the value for sys_dictionary_classify.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_classify.name
     *
     * @return the value of sys_dictionary_classify.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_classify.name
     *
     * @param name the value for sys_dictionary_classify.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary_classify.dic_key
     *
     * @return the value of sys_dictionary_classify.dic_key
     *
     * @mbggenerated
     */
    public String getDicKey() {
        return dicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary_classify.dic_key
     *
     * @param dicKey the value for sys_dictionary_classify.dic_key
     *
     * @mbggenerated
     */
    public void setDicKey(String dicKey) {
        this.dicKey = dicKey == null ? null : dicKey.trim();
    }

	public List<SysDictionary> getSysDicList() {
		return sysDicList;
	}

	public void setSysDicList(List<SysDictionary> sysDicList) {
		this.sysDicList = sysDicList;
	}
}