package com.gionee.baserom.search.util;

import java.util.HashMap;
/**
 * 国家代码
 * @author lzw
 *
 */
public class CurrencyCode {
    public static HashMap<String, String> mCurrencyCode = new HashMap<String, String>();

    static { 
        mCurrencyCode.put("CNY","人民币");
        mCurrencyCode.put("AED","阿联酋迪拉姆");
        mCurrencyCode.put("AFN","阿富汗尼");
        mCurrencyCode.put("AMD","亚美尼亚德拉姆");
        mCurrencyCode.put("ARS","阿根廷比索");
        mCurrencyCode.put("AUD","澳大利亚元");
        mCurrencyCode.put("AZN","阿塞拜疆马纳特");
        mCurrencyCode.put("BAM","波黑马克");
        mCurrencyCode.put("BBD","巴巴多斯元");
        mCurrencyCode.put("BDT","孟加拉塔卡");
        mCurrencyCode.put("BGN","保加利亚列弗");
        mCurrencyCode.put("BMD","百慕大元");
        mCurrencyCode.put("BOB","玻利维亚诺");
        mCurrencyCode.put("BRL","巴西雷亚尔");
        mCurrencyCode.put("BSD","巴哈马元");
        mCurrencyCode.put("BWP","博茨瓦纳普拉");
        mCurrencyCode.put("BYR","白俄罗斯卢布");
        mCurrencyCode.put("CAD","加拿大元");
        mCurrencyCode.put("CHF","瑞士法郎");
        mCurrencyCode.put("CLP","智利比索");
        mCurrencyCode.put("COP","哥伦比亚比索");
        mCurrencyCode.put("CRC","哥斯达黎加科朗");
        mCurrencyCode.put("CUP","古巴比索");
        mCurrencyCode.put("CVE","佛得角埃斯库多");
        mCurrencyCode.put("CZK","捷克克朗");
        mCurrencyCode.put("DJF","吉布提法郎");
        mCurrencyCode.put("DKK","丹麦克朗");
        mCurrencyCode.put("DOP","多米尼加比索");
        mCurrencyCode.put("DZD","阿尔及利亚第纳尔");
        mCurrencyCode.put("EGP","埃及镑");
        mCurrencyCode.put("ETB","埃塞尔比亚比尔");
        mCurrencyCode.put("EUR","欧元");
        mCurrencyCode.put("FJD","斐济元");
        mCurrencyCode.put("GBP","英镑");
        mCurrencyCode.put("GEL","格鲁吉亚拉里");
        mCurrencyCode.put("GHS","加纳塞地");
        mCurrencyCode.put("GNF","几内亚法郎");
        mCurrencyCode.put("GTQ","危地马拉格查尔");
        mCurrencyCode.put("HKD","港元");
        mCurrencyCode.put("HNL","洪都拉斯伦皮拉");
        mCurrencyCode.put("HRK","克罗地亚库纳");
        mCurrencyCode.put("HTG","海地古德");
        mCurrencyCode.put("HUF","匈牙利福林");
        mCurrencyCode.put("IDR","印尼盾");
        mCurrencyCode.put("ILS","以色列谢克尔");
        mCurrencyCode.put("INR","印度卢比");
        mCurrencyCode.put("IQD","伊拉克第纳尔");
        mCurrencyCode.put("IRR","伊朗里亚尔");
        mCurrencyCode.put("ISK","冰岛克朗");
        mCurrencyCode.put("JMD","牙买加元");
        mCurrencyCode.put("JOD","约旦第纳尔");
        mCurrencyCode.put("JPY","日元");
        mCurrencyCode.put("KES","肯尼亚先令");
        mCurrencyCode.put("KHR","柬埔寨瑞尔");
        mCurrencyCode.put("KPW","朝鲜圆");
        mCurrencyCode.put("KRW","韩元");
        mCurrencyCode.put("KWD","科威特第纳尔");
        mCurrencyCode.put("KZT","哈萨克坚戈");
        mCurrencyCode.put("LBP","黎巴嫩镑");
        mCurrencyCode.put("LKR","斯里兰卡卢比");
        mCurrencyCode.put("LSL","莱索托洛提");
        mCurrencyCode.put("LYD","利比亚第纳尔");
        mCurrencyCode.put("MAD","摩洛哥迪拉姆");
        mCurrencyCode.put("MDL","摩尔多瓦列伊");
        mCurrencyCode.put("MKD","马其顿第纳尔");
        mCurrencyCode.put("MMK","缅甸缅元");
        mCurrencyCode.put("MNT","蒙古图格里克");
        mCurrencyCode.put("MOP","澳门元");
        mCurrencyCode.put("MVR","马尔代夫拉菲亚");
        mCurrencyCode.put("MXN","墨西哥比索");
        mCurrencyCode.put("MYR","马来西亚令吉");
        mCurrencyCode.put("NAD","纳米比亚元");
        mCurrencyCode.put("NGN","尼日利亚奈拉");
        mCurrencyCode.put("NIO","尼加拉瓜科多巴");
        mCurrencyCode.put("NOK","挪威克朗");
        mCurrencyCode.put("NPR","尼泊尔卢比");
        mCurrencyCode.put("NZD","新西兰元");
        mCurrencyCode.put("OMR","阿曼里亚尔");
        mCurrencyCode.put("PEN","秘鲁新索尔");
        mCurrencyCode.put("PHP","菲律宾比索");
        mCurrencyCode.put("PKR","巴基斯坦卢比");
        mCurrencyCode.put("PLN","波兰兹罗提");
        mCurrencyCode.put("PYG","巴拉圭瓜拉尼");
        mCurrencyCode.put("QAR","卡塔尔里亚尔");
        mCurrencyCode.put("RON","罗马尼亚新列伊");
        mCurrencyCode.put("RSD","塞尔维亚第纳尔");
        mCurrencyCode.put("RUB","卢布");
        mCurrencyCode.put("RWF","卢旺达法郎");
        mCurrencyCode.put("SAR","沙特里亚尔");
        mCurrencyCode.put("SDG","苏丹镑");
        mCurrencyCode.put("SEK","瑞典克朗");
        mCurrencyCode.put("SGD","新加坡元");
        mCurrencyCode.put("SLL","塞拉利昂利昂");
        mCurrencyCode.put("SOS","索马里先令");
        mCurrencyCode.put("SRD","苏里南元");
        mCurrencyCode.put("SYP","叙利亚镑");
        mCurrencyCode.put("THB","泰铢");
        mCurrencyCode.put("TND","突尼斯第纳尔");
        mCurrencyCode.put("TOP","汤加潘加");
        mCurrencyCode.put("TRY","土耳其新里拉");
        mCurrencyCode.put("TTD","特立尼达和多巴哥元");
        mCurrencyCode.put("TWD","新台币");
        mCurrencyCode.put("TZS","坦桑尼亚先令");
        mCurrencyCode.put("UAH","乌克兰格里夫纳");
        mCurrencyCode.put("UGX","乌干达先令");
        mCurrencyCode.put("USD","美元");
        mCurrencyCode.put("UYU","乌拉圭新比索");
        mCurrencyCode.put("UZS","乌兹别克斯坦索姆");
        mCurrencyCode.put("VEF","委内瑞拉玻利瓦尔");
        mCurrencyCode.put("VND","越南盾");
        mCurrencyCode.put("XAF","中非法郎");
        mCurrencyCode.put("XOF","西非法郎");
        mCurrencyCode.put("ZAR","南非兰特");
    }

}
